const DATASETS = {
  nl: [
    {l:"Schiphol Airport", r:["reiziger","piloot","steward","douanier","bagagemedewerker","beveiliger","grondsteward","taxichauffeur"]},
    {l:"De Efteling", r:["bezoeker","attractiemedewerker","horecamedewerker","entertainer","technicus","beveiliger","fotograaf","schoonmaker"]},
    {l:"Avonturenpark Hellendoorn", r:["bezoeker","attractiemedewerker","badmeester","horecamedewerker","technicus","ouder","animatiemedewerker","beveiliger"]},
    {l:"De Holterberg", r:["wandelaar","fietser","boswachter","fotograaf","natuurgids","hardloper","toerist","vrijwilliger"]},
    {l:"Rijssen centrum", r:["winkelier","bezoeker","marktkoopman","bezorger","horecamedewerker","fietser","gemeenteambtenaar","politieagent"]},
    {l:"De Grolsch Veste", r:["supporter","speler","steward","trainer","scheidsrechter","cameraman","horecamedewerker","journalist"]},
    {l:"Preston Palace Almelo", r:["gast","buffetmedewerker","bowler","barmedewerker","receptionist","entertainer","schoonmaker","technicus"]},
    {l:"Giethoorn", r:["toerist","fluisterbootschipper","bewoner","fotograaf","horecamedewerker","gids","fietser","bootverhuurder"]},
    {l:"Utrecht Centraal", r:["reiziger","conducteur","machinist","servicemedewerker","forens","kioskmedewerker","beveiliger","schoonmaker"]},
    {l:"Rijksmuseum Amsterdam", r:["bezoeker","suppoost","gids","conservator","restaurator","fotograaf","receptionist","schoolkind"]},
    {l:"De Keukenhof", r:["bezoeker","hovenier","fotograaf","bloementeler","gids","horecamedewerker","schoonmaker","touringcarchauffeur"]},
    {l:"Johan Cruijff ArenA", r:["supporter","speler","trainer","steward","cameraman","scheidsrechter","horecamedewerker","journalist"]},
    {l:"Ahoy Rotterdam", r:["bezoeker","artiest","beveiliger","lichttechnicus","geluidstechnicus","horecamedewerker","organisator","stagehand"]},
    {l:"Diergaarde Blijdorp", r:["dierenverzorger","bezoeker","dierenarts","gids","horecamedewerker","bioloog","fotograaf","schoonmaker"]},
    {l:"Burgers’ Zoo Arnhem", r:["dierenverzorger","bezoeker","dierenarts","gids","horecamedewerker","bioloog","fotograaf","schoonmaker"]},
    {l:"Madurodam", r:["bezoeker","gids","medewerker","fotograaf","technicus","schoolkind","horecamedewerker","schoonmaker"]},
    {l:"Kinderdijk", r:["molenaar","toerist","fietser","gids","fotograaf","waterbeheerder","bewoner","vrijwilliger"]},
    {l:"De Pier Scheveningen", r:["toerist","horecamedewerker","visser","fotograaf","bungeejumper","strandwacht","winkelmedewerker","wandelaar"]},
    {l:"Walibi Holland", r:["bezoeker","attractiemedewerker","technicus","horecamedewerker","beveiliger","fotograaf","ouder","schoonmaker"]},
    {l:"Beekse Bergen", r:["ranger","bezoeker","dierenverzorger","safaribuschauffeur","bioloog","fotograaf","horecamedewerker","receptionist"]},
    {l:"TT Circuit Assen", r:["coureur","monteur","toeschouwer","marshal","journalist","fotograaf","teammanager","horecamedewerker"]},
    {l:"Euromast Rotterdam", r:["toerist","liftmedewerker","horecamedewerker","fotograaf","receptionist","schoonmaker","gids","technicus"]},
    {l:"Zaanse Schans", r:["toerist","molenaar","kaasmaker","klompenmaker","fotograaf","gids","winkelier","bewoner"]},
    {l:"Nationaal Park De Hoge Veluwe", r:["fietser","wandelaar","boswachter","fotograaf","natuurgids","bezoeker","wildspotter","medewerker"]}
  ],
  eu: [
    {l:"Eiffeltoren", r:["toerist","liftmedewerker","beveiliger","gids","fotograaf","souvenirverkoper","monteur","horecamedewerker"]},
    {l:"Louvre", r:["bezoeker","suppoost","gids","conservator","restaurator","schoolkind","fotograaf","beveiliger"]},
    {l:"Disneyland Paris", r:["bezoeker","attractiemedewerker","figuur","horecamedewerker","technicus","beveiliger","fotograaf","schoonmaker"]},
    {l:"Colosseum Rome", r:["toerist","gids","archeoloog","beveiliger","historicus","fotograaf","ticketmedewerker","restaurator"]},
    {l:"Vaticaanse Musea", r:["bezoeker","gids","bewaker","conservator","priester","fotograaf","restaurator","receptionist"]},
    {l:"Sagrada Família", r:["toerist","gids","bouwvakker","architect","beveiliger","fotograaf","kerkganger","receptionist"]},
    {l:"Piazza San Marco Venetië", r:["toerist","gondelier","ober","fotograaf","bewoner","straatmuzikant","politieagent","winkelier"]},
    {l:"Neuschwanstein", r:["toerist","gids","bewaker","historicus","fotograaf","receptionist","schoonmaker","buschauffeur"]},
    {l:"Slot Schönbrunn", r:["toerist","gids","tuinman","conservator","bewaker","fotograaf","historicus","receptionist"]},
    {l:"Karlsbrücke Praag", r:["toerist","straatmuzikant","kunstenaar","fotograaf","politieagent","gids","verkoper","bewoner"]},
    {l:"Akropolis Athene", r:["toerist","archeoloog","gids","bewaker","historicus","fotograaf","restaurator","student"]},
    {l:"Oia op Santorini", r:["toerist","fotograaf","hotelmedewerker","ober","bewoner","taxichauffeur","gids","winkelier"]},
    {l:"Blue Lagoon IJsland", r:["badgast","receptionist","badmeester","toerist","masseur","schoonmaker","horecamedewerker","chauffeur"]},
    {l:"Tivoli Gardens Kopenhagen", r:["bezoeker","attractiemedewerker","horecamedewerker","technicus","muzikant","beveiliger","fotograaf","tuinman"]},
    {l:"LEGOLAND Billund", r:["bezoeker","attractiemedewerker","bouwer","horecamedewerker","technicus","ouder","fotograaf","winkelmedewerker"]},
    {l:"Brandenburger Tor", r:["toerist","gids","fotograaf","politieagent","fietser","journalist","straatartiest","bewoner"]},
    {l:"Oktoberfest op de Theresienwiese", r:["bezoeker","ober","brouwer","muzikant","beveiliger","kok","organisator","politieagent"]},
    {l:"Trevi-fontein", r:["toerist","fotograaf","gids","politieagent","straatverkoper","bewoner","schoonmaker","reisleider"]},
    {l:"Mont Saint-Michel", r:["toerist","gids","monnik","horecamedewerker","fotograaf","bewaker","winkelier","buschauffeur"]},
    {l:"Tower of London", r:["toerist","Yeoman Warder","bewaker","gids","historicus","fotograaf","conservator","receptionist"]},
    {l:"Big Ben & Westminster", r:["toerist","parlementariër","politieagent","gids","fotograaf","journalist","ambtenaar","beveiliger"]},
    {l:"Guggenheim Museum Bilbao", r:["bezoeker","suppoost","gids","conservator","fotograaf","receptionist","kunstenaar","schoonmaker"]},
    {l:"Alhambra Granada", r:["toerist","gids","tuinman","bewaker","historicus","fotograaf","restaurator","receptionist"]},
    {l:"Atomium Brussel", r:["toerist","gids","liftmedewerker","fotograaf","horecamedewerker","beveiliger","technicus","receptionist"]}
  ],
  world: [
    {l:"Times Square New York", r:["toerist","taxichauffeur","politieagent","winkelmedewerker","straatartiest","fotograaf","kantoormedewerker","bezorger"]},
    {l:"Grand Central Terminal", r:["reiziger","conducteur","forens","politieagent","winkelmedewerker","toerist","stationsmedewerker","schoonmaker"]},
    {l:"Statue of Liberty", r:["toerist","gids","veerbootmedewerker","parkwachter","fotograaf","beveiliger","receptionist","schoolkind"]},
    {l:"Golden Gate Bridge", r:["toerist","fietser","automobilist","fotograaf","wegwerker","politieagent","hardloper","gids"]},
    {l:"Grand Canyon", r:["ranger","toerist","wandelaar","fotograaf","gids","helikopterpiloot","kampeerder","reddingswerker"]},
    {l:"Machu Picchu", r:["toerist","gids","archeoloog","bewaker","fotograaf","historicus","wandelaar","treinreiziger"]},
    {l:"Christus de Verlosser Rio", r:["toerist","gids","fotograaf","beveiliger","treinmedewerker","souvenirverkoper","reisleider","schoonmaker"]},
    {l:"Shibuya Crossing Tokio", r:["forens","toerist","student","fotograaf","winkelmedewerker","politieagent","zakenman","bezorger"]},
    {l:"Tokyo Skytree", r:["toerist","liftmedewerker","fotograaf","beveiliger","winkelmedewerker","receptionist","technicus","horecamedewerker"]},
    {l:"Sydney Opera House", r:["toerist","muzikant","technicus","gids","beveiliger","fotograaf","bezoeker","horecamedewerker"]},
    {l:"Great Barrier Reef", r:["duiker","duikinstructeur","marien bioloog","toerist","schipper","fotograaf","ranger","snorkelaar"]},
    {l:"Burj Khalifa", r:["toerist","liftmedewerker","beveiliger","hotelgast","receptionist","fotograaf","technicus","horecamedewerker"]},
    {l:"Petra in Jordanië", r:["toerist","gids","archeoloog","fotograaf","bewaker","paardenverzorger","historicus","reisleider"]},
    {l:"Piramides van Gizeh", r:["toerist","gids","archeoloog","fotograaf","bewaker","kameeldrijver","historicus","verkoper"]},
    {l:"Taj Mahal", r:["toerist","gids","fotograaf","bewaker","tuinman","historicus","receptionist","schoonmaker"]},
    {l:"Chinese Muur bij Badaling", r:["toerist","gids","fotograaf","bewaker","verkoper","wandelaar","buschauffeur","historicus"]},
    {l:"Marina Bay Sands", r:["hotelgast","receptionist","toerist","croupier","beveiliger","zwemmer","horecamedewerker","schoonmaker"]},
    {l:"Table Mountain Kaapstad", r:["toerist","wandelaar","kabelbaanmedewerker","fotograaf","gids","ranger","reddingswerker","hardloper"]},
    {l:"Serengeti National Park", r:["ranger","toerist","safarichauffeur","fotograaf","bioloog","gids","kok","reisleider"]},
    {l:"Niagara Falls", r:["toerist","bootmedewerker","gids","fotograaf","receptionist","regenponchoverkoper","buschauffeur","ranger"]},
    {l:"Mount Fuji", r:["wandelaar","gids","fotograaf","toerist","berghutmedewerker","buschauffeur","reddingswerker","pelgrim"]},
    {l:"Chichén Itzá", r:["toerist","gids","archeoloog","fotograaf","bewaker","historicus","verkoper","onderzoeker"]},
    {l:"Angkor Wat", r:["toerist","gids","monnik","fotograaf","archeoloog","bewaker","tuktukchauffeur","restaurator"]},
    {l:"Banff National Park", r:["ranger","wandelaar","toerist","fotograaf","kampeerder","gids","skiër","reddingswerker"]}
  ],
  films: [
    {l:"Hogwarts", r:["leerling","professor","schoolhoofd","conciërge","bibliothecaris","spelwachter","huiself","geest"]},
    {l:"Death Star", r:["stormtrooper","officier","piloot","monteur","droid","gevangene","commandant","technicus"]},
    {l:"Titanic", r:["passagier eerste klas","passagier derde klas","kapitein","machinist","ober","muzikant","steward","uitkijk"]},
    {l:"Jurassic Park", r:["paleontoloog","parkwachter","wetenschapper","toerist","dierenarts","chauffeur","systeembeheerder","jager"]},
    {l:"The Shire", r:["hobbit","tuinman","tovenaar","herbergier","boer","postbode","reiziger","feestgast"]},
    {l:"Wonka’s chocoladefabriek", r:["chocolatier","kind","ouder","fabrieksarbeider","uitvinder","gids","proever","boekhouder"]},
    {l:"Ghostbusters-hoofdkwartier", r:["ghostbuster","receptionist","monteur","wetenschapper","klant","verslaggever","agent","spook"]},
    {l:"Hill Valley 1955", r:["scholier","uitvinder","muzikant","politieagent","cafémedewerker","leraar","automonteur","tijdreiziger"]},
    {l:"Port Royal", r:["piraat","marineofficier","gouverneur","smid","koopman","gevangene","zeeman","herbergier"]},
    {l:"Het huis van Kevin McCallister", r:["kind","inbreker","buurman","politieagent","pizzabezorger","familielid","postbode","kerstbezoeker"]},
    {l:"Andy’s kamer", r:["cowboypop","ruimteheld","dinosaurus","aardappelpop","pop","speelgoedauto","kind","speelgoedverzamelaar"]},
    {l:"Barbie Land", r:["Barbie","Ken","president-Barbie","dokter-Barbie","bouwvakker-Barbie","strand-Ken","bezoeker","verkoper"]},
    {l:"Arendelle", r:["prinses","zus","sneeuwpop","bergman","paleiswacht","handelaar","koninklijke gast","rendierverzorger"]},
    {l:"P. Sherman 42 Wallaby Way Sydney", r:["clownvis","doktersvis","kogelvis","zeester","garnaal","pelikaan","tandarts","patiënt"]},
    {l:"Men in Black-hoofdkwartier", r:["agent","alien","receptionist","wapentechnicus","onderzoeker","beveiliger","getuige","monteur"]},
    {l:"Hunger Games-arena", r:["tribut","spelmaker","mentor","sponsor","cameraman","medicus","bewaker","presentator"]},
    {l:"Seahaven", r:["Truman","buurman","winkelier","acteur","regisseur","cameratechnicus","figurant","radiomaker"]},
    {l:"Casino Royale", r:["geheim agent","croupier","tegenstander","beveiliger","ober","gokker","hotelgast","kaartdealer"]},
    {l:"Pride Rock", r:["leeuw","leeuwin","welp","mandril","stokstaartje","wrattenzwijn","hyena","vogel"]},
    {l:"The Grand Budapest Hotel", r:["conciërge","lobbyboy","hotelgast","eigenaar","kok","piccolo","rechercheur","schoonmaker"]},
    {l:"Nakatomi Plaza", r:["politieagent","kantoormedewerker","beveiliger","gijzelaar","terrorist","technicus","chauffeur","journalist"]},
    {l:"Mordor", r:["ork","hobbit","tovenaar","soldaat","nazgûl","gevangene","boodschapper","reiziger"]},
    {l:"Amity Island", r:["badgast","politiechef","visser","toerist","bioloog","strandwacht","bootkapitein","journalist"]},
    {l:"Monsters, Inc.", r:["monster","kind","deurtechnicus","receptionist","manager","schoonmaker","beveiliger","monteur"]}
  ],
  bijbel: [
    {l:"Hof van Eden", r:["Adam","Eva","engel","tuinier","dierenverzorger","wandelaar","vruchtenplukker","bewaker"]},
    {l:"Ark van Noach", r:["Noach","familielid","dierenverzorger","timmerman","voedselbeheerder","uitkijk","schoonmaker","passagier"]},
    {l:"Toren van Babel", r:["bouwvakker","steenbakker","voorman","architect","arbeider","handelaar","waterdrager","toeschouwer"]},
    {l:"Mamre bij Abraham", r:["Abraham","Sara","herder","knecht","reiziger","waterdrager","kok","bezoeker"]},
    {l:"Paleis van de farao bij Jozef", r:["Jozef","farao","hofdienaar","graanbeheerder","schrijver","wachter","droomuitlegger","bezoeker"]},
    {l:"Nijl bij baby Mozes", r:["Mirjam","dochter van de farao","dienstmeisje","visser","wachter","moeder","bootvaarder","voorbijganger"]},
    {l:"Berg Sinaï", r:["Mozes","Aäron","oudste","Israëliet","wachter","herder","kind","boodschapper"]},
    {l:"Jericho", r:["Jozua","priester","trompetblazer","soldaat","inwoner","wachter","drager","verkenner"]},
    {l:"Dal van Ela", r:["David","Goliath","soldaat","herder","wapendrager","koning Saul","broer van David","toeschouwer"]},
    {l:"Tempel van Salomo", r:["priester","Leviet","muzikant","wachter","bouwer","bezoeker","schrijver","koninklijke dienaar"]},
    {l:"Berg Karmel", r:["Elia","priester","koning","dienaar","waterdrager","toeschouwer","boodschapper","wachter"]},
    {l:"Schip van Jona", r:["Jona","kapitein","zeeman","roeier","handelaar","passagier","uitkijk","stuurman"]},
    {l:"Leeuwenkuil van Daniël", r:["Daniël","koning Darius","wachter","hofdienaar","schrijver","soldaat","boodschapper","adviseur"]},
    {l:"Bethlehem", r:["Maria","Jozef","herder","wijze","herbergier","reiziger","engel","dorpsbewoner"]},
    {l:"Kana", r:["Jezus","Maria","bruid","bruidegom","dienaar","gast","ceremoniemeester","muzikant"]},
    {l:"Meer van Galilea", r:["Jezus","visser","discipel","stuurman","roeier","passagier","nettenmaker","uitkijk"]},
    {l:"Jericho bij Zacheüs", r:["Zacheüs","Jezus","discipel","belastingbetaler","koopman","kind","omstander","huisbediende"]},
    {l:"Bovenzaal in Jeruzalem", r:["Jezus","discipel","gastheer","dienaar","brooddrager","waterdrager","tafelbediende","boodschapper"]},
    {l:"Getsemane", r:["Jezus","discipel","wachter","soldaat","dienaar","priesterlijke bode","tuinman","omstander"]},
    {l:"Golgotha", r:["soldaat","omstander","discipel","Maria","priester","wachter","reiziger","boodschapper"]},
    {l:"Damascusweg", r:["Paulus","reiziger","metgezel","soldaat","handelaar","boodschapper","voorbijganger","gids"]},
    {l:"Efeze", r:["Paulus","koopman","zilversmid","gelovige","stadbewoner","bewaker","reiziger","schrijver"]},
    {l:"Patmos", r:["Johannes","gevangene","wachter","visser","schrijver","reiziger","soldaat","eilandbewoner"]},
    {l:"Ninevé", r:["Jona","inwoner","koning","handelaar","wachter","priester","kind","boodschapper"]}
  ],
  geschiedenis: [
    {l:"Colosseum", r:["gladiator","senator","toeschouwer","handelaar","bewaker","keizerlijke gast","dierenverzorger","omroeper"]},
    {l:"Forum Romanum", r:["koopman","senator","soldaat","priester","burger","schrijver","advocaat","slaaf"]},
    {l:"Pompeï", r:["bakker","koopman","soldaat","priester","burger","schrijver","arts","herbergier"]},
    {l:"Vikingschip van Oseberg", r:["stuurman","krijger","handelaar","scheepsbouwer","uitkijk","roeier","navigator","hoofdman"]},
    {l:"Kasteel van Carcassonne", r:["ridder","boogschutter","kok","smid","kasteelheer","wachter","boodschapper","genezer"]},
    {l:"Werkplaats van Leonardo da Vinci", r:["Leonardo","leerling","model","opdrachtgever","schilder","uitvinder","houtbewerker","boodschapper"]},
    {l:"Tenochtitlan", r:["koopman","boer","priester","krijger","visser","ambachtsman","belastinginner","drager"]},
    {l:"Batavia van de VOC", r:["kapitein","matroos","koopman","scheepsarts","kok","timmerman","kanonnier","stuurman"]},
    {l:"Atelier van Rembrandt", r:["schilder","leerling","model","kunsthandelaar","opdrachtgever","pigmentmaker","bezoeker","lijstenmaker"]},
    {l:"Paleis van Versailles", r:["koning","hofdame","lakei","kok","musicus","wachter","diplomaat","tuinman"]},
    {l:"Bastille 1789", r:["revolutionair","soldaat","gevangene","drukker","koopman","journalist","burger","wachter"]},
    {l:"Waterloo 1815", r:["infanterist","cavalerist","officier","arts","boodschapper","kanonnier","wagenmenner","kampkok"]},
    {l:"Titanic 1912", r:["passagier","kapitein","machinist","ober","muzikant","steward","uitkijk","marconist"]},
    {l:"Loopgraven van de Somme", r:["soldaat","officier","brancardier","arts","boodschapper","kok","uitkijk","telefonist"]},
    {l:"Anne Frank Huis", r:["onderduiker","verzetslid","helper","bezoeker","historicus","bewaker","gids","buurman"]},
    {l:"Omaha Beach 1944", r:["soldaat","medic","radio-operator","officier","schutter","monteur","matroos","journalist"]},
    {l:"Normandië bij D-Day", r:["parachutist","soldaat","boer","medic","officier","verzetslid","chauffeur","journalist"]},
    {l:"Mission Control Houston 1969", r:["vluchtleider","ingenieur","communicator","arts","computerexpert","astronautentrainer","journalist","technicus"]},
    {l:"Checkpoint Charlie", r:["grenswacht","reiziger","journalist","soldaat","tolk","familielid","politieagent","diplomaat"]},
    {l:"Woodstock 1969", r:["muzikant","festivalganger","geluidstechnicus","fotograaf","organisator","verkoper","journalist","EHBO’er"]},
    {l:"Brandenburger Tor 1989", r:["Oost-Berlijner","West-Berlijner","grenswacht","journalist","student","muzikant","fotograaf","politieagent"]},
    {l:"Hiroshima 1945", r:["inwoner","arts","soldaat","verpleegkundige","journalist","brandweerman","ambtenaar","reddingswerker"]},
    {l:"Ellis Island", r:["immigrant","arts","ambtenaar","tolk","bewaker","familielid","inspecteur","scheepspassagier"]},
    {l:"Cape Canaveral bij Apollo 11", r:["astronaut","ingenieur","technicus","journalist","beveiliger","arts","fotograaf","vluchtleider"]}
  ],
  sprookjes: [
    {l:"Bal van Assepoester", r:["Assepoester","prins","stiefzus","hofdame","lakei","muzikant","koetsier","gast"]},
    {l:"Huis van de zeven dwergen", r:["Sneeuwwitje","dwerg","jager","reiziger","houtvester","kok","mijnwerker","bezoeker"]},
    {l:"Snoephuis van Hans en Grietje", r:["Hans","Grietje","heks","bakker","verdwaald kind","houtvester","reiziger","snoepmaker"]},
    {l:"Bos van Roodkapje", r:["Roodkapje","wolf","jager","grootmoeder","houtvester","reiziger","mandenverkoper","boswachter"]},
    {l:"Bakstenen huis van de drie biggetjes", r:["biggetje","wolf","metselaar","timmerman","boer","buurman","dakdekker","bezoeker"]},
    {l:"Kasteel van Doornroosje", r:["prinses","prins","fee","wachter","kok","hofdame","tuinman","lakei"]},
    {l:"Toren van Rapunzel", r:["Rapunzel","prins","heks","wachter","reiziger","boer","vlechter","boodschapper"]},
    {l:"Neverland", r:["Peter Pan","Tinker Bell","verdwaald kind","piraat","zeemeermin","indiaanse krijger","krokodil","kapitein"]},
    {l:"Wonderland", r:["Alice","Witte Konijn","Hoedenmaker","Hartenkoningin","kat","kaartwachter","rups","theegast"]},
    {l:"Emerald City", r:["Dorothy","tovenaar","wachter","vogelverschrikker","blikken man","leeuw","heks","inwoner"]},
    {l:"Kasteel van Belle en het Beest", r:["Belle","Beest","butler","kok","dienaar","gast","uitvinder","dorpsbewoner"]},
    {l:"Agrabah", r:["Aladdin","prinses","sultan","wachter","koopman","dief","geest","straatverkoper"]},
    {l:"Atlantica", r:["zeemeermin","zeekoning","krab","vis","heks","bewaker","muzikant","prins"]},
    {l:"100 Acre Wood", r:["beer","tijger","konijn","biggetje","uil","jongen","ezel","bezoeker"]},
    {l:"Camelot", r:["koning Arthur","ridder","Merlijn","hofdame","smid","wachter","boodschapper","dienaar"]},
    {l:"Sherwood Forest", r:["Robin Hood","boogschutter","sheriff","reiziger","monnik","koopman","woudloper","wachter"]},
    {l:"Olympus uit Hercules", r:["god","held","boodschapper","muze","bewaker","sterfelijke","monsterverslaander","dienaar"]},
    {l:"Arendelle", r:["prinses","sneeuwpop","bergman","paleiswacht","handelaar","gast","rendierverzorger","kok"]},
    {l:"Nevermore Academy", r:["leerling","leraar","directeur","conciërge","monster","ouder","bewaker","bibliothecaris"]},
    {l:"Hyrule Castle", r:["held","prinses","wachter","kok","handelaar","smid","boodschapper","monster"]},
    {l:"Mushroom Kingdom", r:["loodgieter","prinses","Toad","Koopa","winkelier","bewaker","racer","bewoner"]},
    {l:"Diagon Alley", r:["tovenaar","winkelier","bankmedewerker","leerling","uilenverkoper","boekenverkoper","toerist","bewaker"]},
    {l:"Narnia", r:["koning","koningin","faun","centaur","bever","heks","ridder","reiziger"]},
    {l:"Rivendell", r:["elf","reiziger","tovenaar","boogschutter","genezer","raadslid","wachter","muzikant"]}
  ],
  dagjeuit: [
    {l:"Huttopia De Veluwe", r:["kampeerder","receptionist","kind","schoonmaker","fietser","horecamedewerker","campingbeheerder","wandelaar"]},
    {l:"Camping De Kleine Wolf", r:["kampeerder","animatiemedewerker","badmeester","receptionist","kind","horecamedewerker","schoonmaker","campingbeheerder"]},
    {l:"Vakantiepark Slagharen", r:["gast","attractiemedewerker","receptionist","badmeester","horecamedewerker","technicus","kind","schoonmaker"]},
    {l:"Center Parcs De Eemhof", r:["gast","badmeester","receptionist","horecamedewerker","fietsenverhuurder","schoonmaker","kind","technische dienst"]},
    {l:"Duinrell", r:["bezoeker","attractiemedewerker","badmeester","kampeerder","horecamedewerker","technicus","ouder","beveiliger"]},
    {l:"Toverland", r:["bezoeker","attractiemedewerker","horecamedewerker","technicus","entertainer","fotograaf","beveiliger","schoonmaker"]},
    {l:"Wildlands Emmen", r:["bezoeker","dierenverzorger","gids","fotograaf","horecamedewerker","dierenarts","kind","schoonmaker"]},
    {l:"Apenheul", r:["bezoeker","dierenverzorger","gids","fotograaf","horecamedewerker","bioloog","kind","schoonmaker"]},
    {l:"NEMO Science Museum", r:["bezoeker","proefjesbegeleider","kind","docent","technicus","receptionist","gids","schoonmaker"]},
    {l:"Spoorwegmuseum Utrecht", r:["bezoeker","machinist","conducteur","gids","conservator","kind","technicus","fotograaf"]},
    {l:"Openluchtmuseum Arnhem", r:["bezoeker","gids","ambachtsman","historicus","fotograaf","vrijwilliger","horecamedewerker","schoolkind"]},
    {l:"Dolfinarium Harderwijk", r:["bezoeker","dierenverzorger","trainer","dierenarts","fotograaf","horecamedewerker","kind","schoonmaker"]},
    {l:"SnowWorld Landgraaf", r:["skiër","snowboarder","instructeur","liftmedewerker","horecamedewerker","verhuurder","monteur","toeschouwer"]},
    {l:"Thermen Bussloo", r:["badgast","saunameester","receptionist","masseur","horecamedewerker","schoonmaker","bezoeker","badmeester"]},
    {l:"GaiaZOO Kerkrade", r:["bezoeker","dierenverzorger","dierenarts","gids","fotograaf","horecamedewerker","kind","schoonmaker"]},
    {l:"Netl de Wildste Tuin", r:["kampeerder","bezoeker","kind","receptionist","horecamedewerker","wandelaar","schoonmaker","beheerder"]},
    {l:"Camping De Noetselerberg", r:["kampeerder","receptionist","kind","badmeester","animatiemedewerker","schoonmaker","fietser","campingbeheerder"]},
    {l:"Museum MORE Gorssel", r:["bezoeker","suppoost","gids","conservator","kunstenaar","receptionist","fotograaf","schoonmaker"]},
    {l:"Paleis Het Loo", r:["bezoeker","gids","tuinman","conservator","bewaker","fotograaf","historicus","receptionist"]},
    {l:"Ouwehands Dierenpark", r:["bezoeker","dierenverzorger","dierenarts","gids","fotograaf","horecamedewerker","kind","schoonmaker"]},
    {l:"Attractiepark Drouwenerzand", r:["bezoeker","attractiemedewerker","horecamedewerker","ouder","kind","technicus","beveiliger","schoonmaker"]},
    {l:"Movie Park Germany", r:["bezoeker","attractiemedewerker","entertainer","horecamedewerker","technicus","beveiliger","fotograaf","schoonmaker"]},
    {l:"Phantasialand", r:["bezoeker","attractiemedewerker","entertainer","horecamedewerker","technicus","beveiliger","fotograaf","schoonmaker"]},
    {l:"Europa-Park", r:["bezoeker","attractiemedewerker","entertainer","horecamedewerker","technicus","beveiliger","fotograaf","hotelgast"]}
  ]
};

const QUESTION_IDEAS = [
  "Wat zou je hier als eerste doen?",
  "Wat zou je hier absoluut niet vergeten mee te nemen?",
  "Wat hoor je hier waarschijnlijk veel?",
  "Wat zou hier het duurste kunnen zijn?",
  "Kom je hier eerder voor plezier, werk of allebei?",
  "Welke kleding past hier het best?",
  "Wat is hier waarschijnlijk het drukste moment?",
  "Wat zou je hier waarschijnlijk fotograferen?",
  "Waar zou je hier het liefst níét verantwoordelijk voor zijn?",
  "Wat zou je hier na een uur zat kunnen zijn?",
  "Met wie kom je hier meestal?",
  "Wat is hier waarschijnlijk streng geregeld?",
  "Waar zou je hier moeten wachten?",
  "Wat zou hier een typische geur zijn?",
  "Wat zou je hier makkelijk kwijt kunnen raken?",
  "Wat zou je hier vooral niet willen missen?"
];