const $=s=>document.querySelector(s);
const screens=['setupScreen','handoffScreen','revealScreen','roundScreen','resultScreen'];
let players=['Eline','Maarten','Juan','Daniëlle'];
let selectedSet='locaties',game=null,timerId=null,remaining=0,timerRunning=false,peeked=false;
let spyBagNames=[],spyBagKey='',previousSpyNames=[];

function savePrefs(){try{localStorage.setItem('spyfallAlgemeenPlayers',JSON.stringify(players));localStorage.setItem('spyfallAlgemeenSet',selectedSet);}catch(e){}}
function loadPrefs(){try{const p=JSON.parse(localStorage.getItem('spyfallAlgemeenPlayers'));if(Array.isArray(p)&&p.length>=3)players=p;const s=localStorage.getItem('spyfallAlgemeenSet');if(s&&(s==='mix'||Object.prototype.hasOwnProperty.call(DATASETS,s)))selectedSet=s;}catch(e){}}
function showScreen(id){screens.forEach(s=>$('#'+s).classList.toggle('hidden',s!==id));scrollTo(0,0)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function renderPlayers(){const c=$('#players');c.innerHTML='';players.forEach((p,i)=>{const row=document.createElement('div');row.className='player';row.innerHTML=`<input maxlength="22" value="${escapeHtml(p)}"><button type="button" class="remove">×</button>`;const inp=row.querySelector('input');inp.addEventListener('input',()=>{players[i]=inp.value;resetSpyRotation();savePrefs()});row.querySelector('button').addEventListener('click',()=>{if(players.length<=3){toast('Minimaal 3 spelers');return}players.splice(i,1);resetSpyRotation();renderPlayers();savePrefs()});c.appendChild(row)});$('#playerCountLabel').textContent=`${players.length} spelers`;$('#spyCount').querySelector('option[value="2"]').disabled=players.length<6;if(players.length<6&&$('#spyCount').value==='2')$('#spyCount').value='1'}
function renderPills(){document.querySelectorAll('.pill').forEach(p=>p.classList.toggle('active',p.dataset.set===selectedSet))}
function randInt(n){if(n<=1)return 0;try{if(window.crypto&&crypto.getRandomValues){const a=new Uint32Array(1),limit=Math.floor(0x100000000/n)*n;do{crypto.getRandomValues(a)}while(a[0]>=limit);return a[0]%n}}catch(e){}return Math.floor(Math.random()*n)}
function shuffled(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=randInt(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
function getPool(){return selectedSet==='mix'?Object.values(DATASETS).flat():(DATASETS[selectedSet]||DATASETS.locaties)}
function cleanedPlayers(){return players.map((x,i)=>x.trim()||`Speler ${i+1}`)}
function resetSpyRotation(){spyBagNames=[];spyBagKey='';previousSpyNames=[]}
function chooseSpyIndices(spyCount){const key=players.join('\u0001'),indices=players.map((_,i)=>i);if(spyCount===1){if(spyBagKey!==key||spyBagNames.length===0){let bag=shuffled(players);if(previousSpyNames.length&&bag.length>1&&bag[0]===previousSpyNames[0]){const j=bag.findIndex(n=>n!==previousSpyNames[0]);if(j>0)[bag[0],bag[j]]=[bag[j],bag[0]]}spyBagNames=bag;spyBagKey=key}const chosenName=spyBagNames.shift();previousSpyNames=[chosenName];return new Set([players.indexOf(chosenName)])}let eligible=indices.filter(i=>!previousSpyNames.includes(players[i]));if(eligible.length<spyCount)eligible=indices;const chosen=shuffled(eligible).slice(0,spyCount);previousSpyNames=chosen.map(i=>players[i]);spyBagNames=[];spyBagKey=key;return new Set(chosen)}
function startGame(){players=cleanedPlayers();if(players.length<3){toast('Minimaal 3 spelers');return}const dup=players.some((p,i)=>players.findIndex(x=>x.toLowerCase()===p.toLowerCase())!==i);if(dup){toast('Gebruik unieke spelersnamen');return}const spyCount=parseInt($('#spyCount').value,10);const pool=getPool(),loc=pool[randInt(pool.length)],order=shuffled(players.map((name,i)=>({name,idx:i}))),spyIndices=chooseSpyIndices(spyCount),roles=shuffled(loc.r);let rc=0;const assignments=players.map((name,i)=>({name,spy:spyIndices.has(i),role:spyIndices.has(i)?'Spion':roles[(rc++)%roles.length]}));game={location:loc.l,assignments,order,current:0,starter:players[randInt(players.length)],minutes:parseInt($('#roundMinutes').value,10)};savePrefs();showHandoff()}
function showHandoff(){const who=game.order[game.current].name;$('#handoffName').textContent=who;$('#readyName').textContent=who;showScreen('handoffScreen')}
function showReveal(){const idx=game.order[game.current].idx,a=game.assignments[idx];$('#revealName').textContent=a.name;$('#secretContent').innerHTML='';$('#secretBox').classList.toggle('spybox',a.spy);$('#seenBtn').disabled=true;peeked=false;$('#coveredContent').classList.remove('hidden');$('#secretContent').classList.add('hidden');$('#secretContent').innerHTML=a.spy?`<div><div class="big-icon" style="font-size:52px">🕵️</div><div class="role spy">JIJ BENT DE SPION</div><div class="hint" style="margin-top:10px">Ontdek de locatie zonder op te vallen.</div></div>`:`<div><div class="tiny">LOCATIE</div><div class="location">${escapeHtml(game.location)}</div><div class="tiny" style="margin-top:20px">JOUW ROL</div><div class="role">${escapeHtml(a.role)}</div></div>`;showScreen('revealScreen')}
function setPeek(show){if(show){$('#coveredContent').classList.add('hidden');$('#secretContent').classList.remove('hidden');peeked=true;$('#seenBtn').disabled=false}else{$('#coveredContent').classList.remove('hidden');$('#secretContent').classList.add('hidden')}}
function nextPlayer(){if(!peeked)return;setPeek(false);game.current++;if(game.current>=game.order.length)startRound();else showHandoff()}
function startRound(){remaining=game.minutes*60;timerRunning=true;updateTimer();clearInterval(timerId);timerId=setInterval(tick,1000);$('#starterText').textContent=`${game.starter} begint met een vraag.`;$('#questionIdeas').innerHTML=shuffled(QUESTION_IDEAS).slice(0,5).map((q,i)=>`<div class="locrow"><span>${i+1}. ${escapeHtml(q)}</span></div>`).join('');$('#locationsList').innerHTML=shuffled(getPool().map(x=>x.l)).map(x=>`<div class="locrow"><span>${escapeHtml(x)}</span></div>`).join('');$('#locationsList').classList.add('hidden');$('#locationsToggle').textContent='Toon locatielijst';$('#timerToggle').textContent='⏸ Pauze';showScreen('roundScreen')}
function tick(){if(!timerRunning)return;remaining=Math.max(0,remaining-1);updateTimer();if(remaining===0){timerRunning=false;clearInterval(timerId);toast('Tijd is om!')}}
function updateTimer(){const m=Math.floor(remaining/60),s=remaining%60;$('#timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;$('#timer').classList.toggle('low',remaining<=60)}
function toggleTimer(){timerRunning=!timerRunning;$('#timerToggle').textContent=timerRunning?'⏸ Pauze':'▶ Verder'}
function endRound(){clearInterval(timerId);timerRunning=false;const spies=game.assignments.filter(a=>a.spy).map(a=>a.name);$('#resultLocation').textContent=game.location;$('#resultSpies').textContent=spies.join(' & ');$('#roleSummary').innerHTML=game.assignments.map(a=>`<div class="locrow"><span><b>${escapeHtml(a.name)}</b></span><span>${a.spy?'🕵️ Spion':escapeHtml(a.role)}</span></div>`).join('');showScreen('resultScreen')}
function addPlayer(){if(players.length>=20){toast('Maximaal 20 spelers');return}players.push(`Speler ${players.length+1}`);resetSpyRotation();renderPlayers();savePrefs();const inputs=document.querySelectorAll('#players input'),last=inputs[inputs.length-1];if(last){last.focus();last.select()}}
function resetAll(){if(confirm('Spelers en instellingen terugzetten?')){try{localStorage.removeItem('spyfallAlgemeenPlayers');localStorage.removeItem('spyfallAlgemeenSet')}catch(e){}players=['Eline','Maarten','Juan','Daniëlle'];selectedSet='locaties';resetSpyRotation();renderPlayers();renderPills();showScreen('setupScreen')}}

$('#addPlayerBtn').onclick=addPlayer;$('#setPills').onclick=e=>{const p=e.target.closest('.pill');if(!p)return;selectedSet=p.dataset.set;renderPills();savePrefs()};$('#startBtn').onclick=startGame;$('#readyBtn').onclick=showReveal;$('#seenBtn').onclick=nextPlayer;$('#timerToggle').onclick=toggleTimer;$('#locationsToggle').onclick=()=>{const l=$('#locationsList'),hidden=l.classList.toggle('hidden');$('#locationsToggle').textContent=hidden?'Toon locatielijst':'Verberg locatielijst'};$('#endRoundBtn').onclick=endRound;$('#againBtn').onclick=()=>{showScreen('setupScreen');setTimeout(startGame,50)};$('#backSetupBtn').onclick=()=>showScreen('setupScreen');$('#resetBtn').onclick=resetAll;
const sb=$('#secretBox');if(window.PointerEvent){sb.addEventListener('pointerdown',e=>{e.preventDefault();setPeek(true)},{passive:false});['pointerup','pointercancel','pointerleave'].forEach(ev=>sb.addEventListener(ev,e=>{e.preventDefault();setPeek(false)},{passive:false}))}else{['touchstart','mousedown'].forEach(ev=>sb.addEventListener(ev,e=>{e.preventDefault();setPeek(true)},{passive:false}));['touchend','touchcancel','mouseup','mouseleave'].forEach(ev=>sb.addEventListener(ev,e=>{e.preventDefault();setPeek(false)},{passive:false}))}
loadPrefs();renderPlayers();renderPills();
