// Extra themasets voor Spyfall. Wordt geladen na data.js.

DATASETS.films = [
  {l:'Hogwarts', r:['tovenaarsleerling','professor','schoolhoofd','conciërge','bibliothecaris','spelwachter','huiself','geest']},
  {l:'Death Star', r:['stormtrooper','officier','piloot','monteur','droid','gevangene','commandant','technicus']},
  {l:'Titanic', r:['passagier eerste klas','passagier derde klas','kapitein','machinist','ober','muzikant','steward','uitkijk']},
  {l:'Jurassic Park', r:['paleontoloog','parkwachter','wetenschapper','toerist','dierenarts','chauffeur','systeembeheerder','jager']},
  {l:'The Shire', r:['hobbit','tuinman','tovenaar','herbergier','boer','postbode','reiziger','feestgast']},
  {l:'Wonka’s chocoladefabriek', r:['chocolatier','kind','ouder','fabrieksarbeider','uitvinder','gids','proever','boekhouder']},
  {l:'The Matrix – kantoorverdieping', r:['hacker','kantoormedewerker','agent','programmeur','telefonist','bewaker','bezorger','bezoeker']},
  {l:'Ghostbusters-hoofdkwartier', r:['ghostbuster','receptionist','monteur','wetenschapper','klant','verslaggever','agent','spook']},
  {l:'Hill Valley in 1955', r:['scholier','uitvinder','muzikant','politieagent','cafémedewerker','leraar','automonteur','tijdreiziger']},
  {l:'Piratenhaven uit Pirates of the Caribbean', r:['piraat','marineofficier','gouverneur','smid','koopman','gevangene','zeeman','herbergier']},
  {l:'Indiana Jones-tempel', r:['archeoloog','gids','schatzoeker','bewaker','soldaat','professor','drager','avonturier']},
  {l:'Het huis uit Home Alone', r:['kind','inbreker','buurman','politieagent','pizzabezorger','familielid','postbode','kerstbezoeker']},
  {l:'Andy’s kamer uit Toy Story', r:['speelgoedcowboy','ruimteheld','dinosaurus','aardappelpop','pop','speelgoedauto','kind','speelgoedverzamelaar']},
  {l:'Barbie Land', r:['Barbie','Ken','president-Barbie','dokter-Barbie','bouwvakker-Barbie','strand-Ken','bezoeker','verkoper']},
  {l:'IJspaleis uit Frozen', r:['ijsprinses','zus','sneeuwpop','bergman','paleiswacht','handelaar','koninklijke gast','rendierverzorger']},
  {l:'Aquarium uit Finding Nemo', r:['clownvis','doktersvis','kogelvis','zeester','garnaal','pelikaan','tandarts','patiënt']},
  {l:'Men in Black-hoofdkwartier', r:['agent','alien','receptionist','wapentechnicus','onderzoeker','beveiliger','getuige','monteur']},
  {l:'Hunger Games-arena', r:['tribut','spelmaker','mentor','sponsor','cameraman','medicus','bewaker','presentator']},
  {l:'Seahaven uit The Truman Show', r:['hoofdpersoon','buurman','winkelier','acteur','regisseur','cameratechnicus','figurant','radiomaker']},
  {l:'James Bond-casino', r:['geheim agent','croupier','tegenstander','beveiliger','ober','gokker','hotelgast','kaartdealer']},
  {l:'Het huis uit E.T.', r:['kind','moeder','broer','alien','wetenschapper','agent','buurkind','leraar']},
  {l:'Pride Rock uit The Lion King', r:['leeuw','leeuwin','welp','mandril','stokstaartje','wrattenzwijn','hyena','vogel']},
  {l:'Apollo 13-ruimtevaartuig', r:['astronaut','vluchtleider','ingenieur','arts','technicus','communicator','simulatorpiloot','journalist']},
  {l:'The Grand Budapest Hotel', r:['conciërge','lobbyboy','hotelgast','eigenaar','kok','piccolo','rechercheur','schoonmaker']}
];

DATASETS.bijbel = [
  {l:'Hof van Eden', r:['Adam','Eva','engel','tuinier','dierenverzorger','wandelaar','vruchtenplukker','bewaker']},
  {l:'Ark van Noach', r:['Noach','familielid','dierenverzorger','timmerman','voedselbeheerder','uitkijk','schoonmaker','passagier']},
  {l:'Toren van Babel', r:['bouwvakker','steenbakker','voorman','architect','arbeider','handelaar','waterdrager','toeschouwer']},
  {l:'Tentenkamp van Abraham', r:['Abraham','Sara','herder','knecht','reiziger','waterdrager','kok','bezoeker']},
  {l:'Paleis van de farao – Jozef', r:['Jozef','farao','hofdienaar','graanbeheerder','schrijver','wachter','droomuitlegger','bezoeker']},
  {l:'Oever van de Nijl – baby Mozes', r:['Mirjam','dochter van de farao','dienstmeisje','visser','wachter','moeder','bootvaarder','voorbijganger']},
  {l:'Brandende braamstruik in Midjan', r:['Mozes','herder','reiziger','schaapherder','waterdrager','kampbewoner','voorbijganger','oudste']},
  {l:'Doortocht door de Rode Zee', r:['Mozes','Israëliet','kind','oudste','soldaat','wagenmenner','herder','waterdrager']},
  {l:'Berg Sinaï', r:['Mozes','Aäron','oudste','Israëliet','wachter','herder','kind','boodschapper']},
  {l:'Muren van Jericho', r:['Jozua','priester','trompetblazer','soldaat','inwoner','wachter','drager','verkenner']},
  {l:'Kamp van Gideon', r:['Gideon','soldaat','uitkijk','waterdrager','fakkeldrager','trompetblazer','boodschapper','kok']},
  {l:'Dal van Ela – David en Goliath', r:['David','Goliath','soldaat','herder','wapendrager','koning Saul','broer van David','toeschouwer']},
  {l:'Tempel van Salomo', r:['priester','Leviet','muzikant','wachter','bouwer','bezoeker','schrijver','koninklijke dienaar']},
  {l:'Berg Karmel – Elia', r:['Elia','priester','koning','dienaar','waterdrager','toeschouwer','boodschapper','wachter']},
  {l:'Schip van Jona in de storm', r:['Jona','kapitein','zeeman','roeier','handelaar','passagier','uitkijk','stuurman']},
  {l:'Leeuwenkuil van Daniël', r:['Daniël','koning Darius','wachter','hofdienaar','schrijver','soldaat','boodschapper','adviseur']},
  {l:'Stal in Bethlehem', r:['Maria','Jozef','herder','wijze','herbergier','reiziger','engel','dorpsbewoner']},
  {l:'Bruiloft in Kana', r:['Jezus','Maria','bruid','bruidegom','dienaar','gast','ceremoniemeester','muzikant']},
  {l:'Boot op het Meer van Galilea', r:['Jezus','visser','discipel','stuurman','roeier','passagier','nettenmaker','uitkijk']},
  {l:'Heuvel bij de spijziging van de vijfduizend', r:['Jezus','discipel','kind','familie','visser','brooddrager','luisteraar','reiziger']},
  {l:'Weg van Jeruzalem naar Jericho – barmhartige Samaritaan', r:['reiziger','Samaritaan','herbergier','priester','Leviet','koopman','ezeldrijver','voorbijganger']},
  {l:'Straat in Jericho – Zacheüs', r:['Zacheüs','Jezus','discipel','belastingbetaler','koopman','kind','omstander','huisbediende']},
  {l:'Bovenzaal – het laatste avondmaal', r:['Jezus','discipel','gastheer','dienaar','brooddrager','waterdrager','tafelbediende','boodschapper']},
  {l:'Hof van Getsemane', r:['Jezus','discipel','wachter','soldaat','dienaar','priesterlijke bode','tuinman','omstander']}
];

DATASETS.geschiedenis = [
  {l:'Egyptische piramidebouw', r:['steenhouwer','architect','arbeider','schrijver','voorman','waterdrager','priester','wachter']},
  {l:'Romeins Colosseum', r:['gladiator','senator','toeschouwer','handelaar','bewaker','keizerlijke gast','dierenverzorger','omroeper']},
  {l:'Forum in Pompeï', r:['koopman','bakker','senator','slaaf','soldaat','priester','burger','schrijver']},
  {l:'Vikingschip', r:['stuurman','krijger','handelaar','scheepsbouwer','uitkijk','roeier','navigator','hoofdman']},
  {l:'Middeleeuws kasteel tijdens een belegering', r:['ridder','boogschutter','kok','smid','kasteelheer','wachter','boodschapper','genezer']},
  {l:'Markt langs de Zijderoute', r:['koopman','kameeldrijver','tolwachter','vertaler','gids','reiziger','soldaat','herbergier']},
  {l:'Mongools ruiterkamp', r:['ruiter','boogschutter','paardenverzorger','verkenner','kok','boodschapper','smid','hoofdman']},
  {l:'Werkplaats van Leonardo da Vinci', r:['Leonardo','leerling','model','opdrachtgever','schilder','uitvinder','houtbewerker','boodschapper']},
  {l:'Azteekse markt in Tenochtitlan', r:['koopman','boer','priester','krijger','visser','ambachtsman','belastinginner','drager']},
  {l:'VOC-schip', r:['kapitein','matroos','koopman','scheepsarts','kok','timmerman','kanonnier','stuurman']},
  {l:'Atelier van Rembrandt', r:['schilder','leerling','model','kunsthandelaar','opdrachtgever','pigmentmaker','bezoeker','lijstenmaker']},
  {l:'Paleis van Versailles', r:['koning','hofdame','lakei','kok','musicus','wachter','diplomaat','tuinman']},
  {l:'Parijs tijdens de Franse Revolutie', r:['revolutionair','soldaat','bakker','drukker','edelman','koopman','journalist','burger']},
  {l:'Slag bij Waterloo', r:['infanterist','cavalerist','officier','arts','boodschapper','kanonnier','wagenmenner','kampkok']},
  {l:'Textielfabriek tijdens de Industriële Revolutie', r:['fabrieksarbeider','machinebediener','voorman','monteur','eigenaar','kindarbeider','magazijnier','stoommachinist']},
  {l:'Treinstation in het Wilde Westen', r:['stationschef','machinist','reiziger','sheriff','postbode','handelaar','conducteur','telegrafist']},
  {l:'Loopgraaf in de Eerste Wereldoorlog', r:['soldaat','officier','brancardier','arts','boodschapper','kok','uitkijk','telefonist']},
  {l:'Onderduikadres in de Tweede Wereldoorlog', r:['onderduiker','verzetslid','gastgezin','koerier','wachter','buurman','radio-operator','voedselbezorger']},
  {l:'Landingsvaartuig op D-Day', r:['soldaat','stuurman','medic','radio-operator','officier','schutter','monteur','matroos']},
  {l:'Missiecontrole van Apollo 11', r:['vluchtleider','ingenieur','communicator','arts','computerexpert','astronautentrainer','journalist','technicus']},
  {l:'Checkpoint bij de Berlijnse Muur', r:['grenswacht','reiziger','journalist','soldaat','tolk','familielid','politieagent','diplomaat']},
  {l:'Woodstock 1969', r:['muzikant','festivalganger','geluidstechnicus','fotograaf','organisator','verkoper','journalist','EHBO’er']},
  {l:'Berlijn tijdens de val van de Muur', r:['inwoner Oost-Berlijn','inwoner West-Berlijn','grenswacht','journalist','student','muzikant','fotograaf','politieagent']},
  {l:'Eerste transcontinentale spoorlijn in Amerika', r:['spoorwegarbeider','ingenieur','machinist','landmeter','kok','smid','investeerder','conducteur']}
];

DATASETS.sprookjes = [
  {l:'Bal van Assepoester', r:['Assepoester','prins','stiefzus','hofdame','lakei','muzikant','koetsier','gast']},
  {l:'Huisje van de zeven dwergen', r:['Sneeuwwitje','dwerg','jager','reiziger','houtvester','kok','mijnwerker','bezoeker']},
  {l:'Snoephuisje van Hans en Grietje', r:['Hans','Grietje','heks','bakker','verdwaald kind','houtvester','reiziger','snoepmaker']},
  {l:'Bos van Roodkapje', r:['Roodkapje','wolf','jager','grootmoeder','houtvester','reiziger','mandenverkoper','boswachter']},
  {l:'Bakstenen huis van de drie biggetjes', r:['biggetje','wolf','metselaar','timmerman','boer','buurman','dakdekker','bezoeker']},
  {l:'Kasteel van Doornroosje', r:['prinses','prins','fee','wachter','kok','hofdame','tuinman','lakei']},
  {l:'Toren van Rapunzel', r:['Rapunzel','prins','heks','wachter','reiziger','boer','vlechtster','boodschapper']},
  {l:'Kasteel boven de bonenstaak', r:['Jaap','reus','kok','gansverzorger','harpspeler','wachter','dienaar','schatbewaarder']},
  {l:'Poppentheater van Pinokkio', r:['Pinokkio','poppenspeler','timmerman','acteur','muzikant','kaartverkoper','kind','toneelmeester']},
  {l:'Piratenbaai van Peter Pan', r:['Peter Pan','piraat','kapitein','verloren jongen','fee','matroos','uitkijk','gevangene']},
  {l:'Theefeest in Wonderland', r:['Alice','hoedenmaker','haas','koningin','konijn','kaartwachter','theeschenker','gast']},
  {l:'Paleis uit Duizend-en-één-nacht', r:['sultan','verteller','wachter','koopman','dienaar','muzikant','adviseur','reiziger']},
  {l:'Markt van Hamelen', r:['rattenvanger','burgemeester','koopman','kind','bakker','muzikant','stadswacht','inwoner']},
  {l:'Paleis van De nieuwe kleren van de keizer', r:['keizer','kleermaker','hofdienaar','kind','wachter','adviseur','wever','toeschouwer']},
  {l:'Vijver van De Kikkerkoning', r:['prinses','kikker','koning','lakei','tuinman','wachter','hofdame','bezoeker']},
  {l:'Betoverd kasteel van Belle en het Beest', r:['Belle','Beest','dienaar','kok','bibliothecaris','gast','tuinman','handelaar']},
  {l:'Herberg van de Bremer stadsmuzikanten', r:['ezel','hond','kat','haan','herbergier','reiziger','muzikant','dief']},
  {l:'Molen van De gelaarsde kat', r:['kat','molenaar','prinses','koning','koetsier','boer','wachter','koopman']},
  {l:'Huis van de drie beren', r:['Goudlokje','grote beer','middelste beer','kleine beer','boswachter','reiziger','buurman','houtvester']},
  {l:'Toren van Repelsteeltje', r:['Repelsteeltje','molenaarster','koning','wachter','spinster','dienaar','boodschapper','schatbewaarder']},
  {l:'Kasteel van De prinses op de erwt', r:['prinses','prins','koningin','lakei','kamermeisje','wachter','matrassenmaker','gast']},
  {l:'IJspaleis van De Sneeuwkoningin', r:['Sneeuwkoningin','kind','reiziger','rendierverzorger','wachter','tuinier','koopman','boodschapper']},
  {l:'Sherwood Forest', r:['Robin Hood','boogschutter','sheriff','reiziger','monnik','koopman','wachter','houtvester']},
  {l:'Camelot', r:['koning Arthur','ridder','hofdame','tovenaar','smid','wachter','boodschapper','kok']}
];

DATASETS.avontuur = [
  {l:'Vertrekhal van een vliegveld', r:['reiziger','piloot','steward','douanier','bagagemedewerker','balie-medewerker','zakenreiziger','beveiliger']},
  {l:'Tropisch all-inclusive resort', r:['vakantieganger','receptionist','barman','badmeester','kok','animatiemedewerker','schoonmaker','excursiegids']},
  {l:'Safarijeep', r:['ranger','toerist','chauffeur','fotograaf','bioloog','gids','wildspotter','monteur']},
  {l:'Cruiseschip', r:['passagier','kapitein','steward','kok','entertainer','barman','technicus','reisleider']},
  {l:'Skichalet', r:['skiër','instructeur','kok','chaletbeheerder','snowboarder','monteur','bergwandelaar','gast']},
  {l:'Camping aan een meer', r:['kampeerder','campingbeheerder','visser','zwemmer','animatiemedewerker','fietser','schoonmaker','kanovaarder']},
  {l:'Tankstation tijdens een roadtrip', r:['automobilist','kassamedewerker','truckchauffeur','monteur','camperaar','motorrijder','reiziger','bezorger']},
  {l:'Nachttrain door Europa', r:['reiziger','conducteur','machinist','backpacker','zakenreiziger','steward','student','controleur']},
  {l:'Berghut vlak onder de top', r:['wandelaar','berggids','huttenwaard','klimmer','reddingswerker','kok','fotograaf','weerkundige']},
  {l:'Duikboot bij een koraalrif', r:['duiker','duikinstructeur','kapitein','marien bioloog','fotograaf','toerist','monteur','bootsman']},
  {l:'Raftingkamp aan een wilde rivier', r:['raftgids','deelnemer','kok','EHBO’er','fotograaf','chauffeur','kampbeheerder','instructeur']},
  {l:'Jungle-expeditiekamp', r:['onderzoeker','gids','kok','fotograaf','bioloog','drager','arts','radio-operator']},
  {l:'Woestijnkamp', r:['reiziger','gids','kameelverzorger','kok','chauffeur','fotograaf','kampbeheerder','archeoloog']},
  {l:'Hostel in een grote stad', r:['backpacker','receptionist','student','schoonmaker','nachtwaker','reisblogger','kamermaat','hostelmanager']},
  {l:'Pretpark tijdens een dagje uit', r:['bezoeker','attractiemedewerker','mascotte','horecamedewerker','technicus','beveiliger','fotograaf','schoonmaker']},
  {l:'Festivalcamping', r:['festivalganger','beveiliger','campingcrew','DJ','foodtruckmedewerker','EHBO’er','fotograaf','organisator']},
  {l:'Camperplaats aan een Noors fjord', r:['camperaar','visser','wandelaar','beheerder','fotograaf','kajakker','fietser','lokale bewoner']},
  {l:'Zeiljacht tussen Griekse eilanden', r:['schipper','zeiler','toerist','kok','duiker','navigator','matroos','havenmeester']},
  {l:'Trekkershut in de Ardennen', r:['wandelaar','mountainbiker','hutbeheerder','klimmer','kok','gids','natuurfotograaf','kampvuurmaker']},
  {l:'Rondreisbus door Japan', r:['reiziger','chauffeur','reisleider','fotograaf','student','tolk','backpacker','zakenreiziger']},
  {l:'Walvissafari op zee', r:['kapitein','toerist','marien bioloog','gids','fotograaf','matroos','vogelaar','reddingswerker']},
  {l:'Huskykamp in Lapland', r:['musher','toerist','hondenverzorger','gids','kok','sneeuwscooterbestuurder','fotograaf','kampbeheerder']},
  {l:'Basecamp van een hoge bergexpeditie', r:['klimmer','sherpa','expeditieleider','arts','kok','meteoroloog','drager','fotograaf']},
  {l:'Eilandhoppen met een veerboot', r:['passagier','kapitein','matroos','backpacker','fietser','horecamedewerker','kaartcontroleur','eilander']}
];
