const DATASETS = {
  nl: [
    {l:'Treinstation', r:['conducteur','reiziger','machinist','kioskmedewerker','servicemedewerker','forens','toerist','schoonmaker']},
    {l:'Camping op de Veluwe', r:['campingbeheerder','kampeerder','animatiemedewerker','receptionist','fietser','kind op vakantie','schoonmaker','boswachter']},
    {l:'Kaasmarkt in Alkmaar', r:['kaasdrager','marktmeester','toerist','kaasverkoper','fotograaf','winkelier','gids','proever']},
    {l:'Strandpaviljoen', r:['ober','badgast','kok','surfer','strandwacht','toerist','afwasser','eigenaar']},
    {l:'Basisschool', r:['leerkracht','leerling','directeur','conciërge','ouder','stagiair','onderwijsassistent','gymleraar']},
    {l:'Voetbalstadion', r:['supporter','scheidsrechter','speler','steward','trainer','journalist','cameraman','verkoper']},
    {l:'Boerderij', r:['boer','dierenarts','loonwerker','stagiair','melkveehouder','monteur','bezoeker','voerleverancier']},
    {l:'Pretpark', r:['bezoeker','attractiemedewerker','mascotte','horecamedewerker','technicus','beveiliger','fotograaf','schoonmaker']},
    {l:'Ziekenhuis', r:['arts','verpleegkundige','patiënt','bezoeker','ambulancebroeder','receptionist','laborant','chirurg']},
    {l:'Supermarkt', r:['caissière','vakkenvuller','klant','filiaalmanager','bakker','slager','bezorger','beveiliger']},
    {l:'Kermis', r:['exploitant','bezoeker','oliebollenverkoper','attractiebediener','kind','beveiliger','prijswinnaar','monteur']},
    {l:'Gemeentehuis', r:['ambtenaar','bezoeker','burgemeester','bode','trouwambtenaar','receptionist','raadslid','journalist']},
    {l:'Waddenveer', r:['kapitein','passagier','matroos','toerist','fietser','horecamedewerker','eilander','kaartcontroleur']},
    {l:'Dierentuin', r:['dierenverzorger','bezoeker','dierenarts','gids','horecamedewerker','fotograaf','bioloog','schoonmaker']},
    {l:'IJsclub op natuurijs', r:['schaatser','baanveger','vrijwilliger','koek-en-zopieverkoper','toeschouwer','EHBO’er','kind','ijsmeester']},
    {l:'Bouwmarkt', r:['klusser','kassamedewerker','vakkenvuller','zaagservice-medewerker','hovenier','schilder','filiaalmanager','bezorger']},
    {l:'Museum', r:['bezoeker','suppoost','gids','conservator','kunstenaar','schoolkind','receptionist','restaurator']},
    {l:'Bruiloft', r:['bruid','bruidegom','videograaf','fotograaf','ceremoniemeester','gast','DJ','trouwambtenaar']},
    {l:'Snackbar', r:['frituurkok','klant','bezorger','kassamedewerker','eigenaar','vaste klant','schoonmaker','leverancier']},
    {l:'Vakantiepark', r:['gast','receptionist','badmeester','animatiemedewerker','technische dienst','schoonmaker','parkmanager','fietsenverhuurder']},
    {l:'Politie bureau', r:['agent','rechercheur','aangever','verdachte','balie-medewerker','wijkagent','forensisch onderzoeker','advocaat']},
    {l:'Bibliotheek', r:['bibliothecaris','bezoeker','student','kind','schrijver','vrijwilliger','docent','medewerker']},
    {l:'Bollenveld', r:['teler','toerist','fotograaf','seizoensarbeider','fietser','exporteur','gids','buurtbewoner']},
    {l:'Haven van Rotterdam', r:['kraanmachinist','schipper','douanier','havenarbeider','vrachtwagenchauffeur','inspecteur','kapitein','planner']}
  ],
  eu: [
    {l:'Berghut in de Alpen', r:['wandelaar','huttenwaard','berggids','skiër','kok','reddingswerker','fotograaf','klimmer']},
    {l:'Pizzeria in Rome', r:['pizzabakker','ober','toerist','vaste klant','afwasser','eigenaar','bezorger','sommelier']},
    {l:'Metro in Parijs', r:['forens','toerist','machinist','controleur','muzikant','student','monteur','kaartverkoper']},
    {l:'Kasteel in Schotland', r:['gids','toerist','beheerder','historicus','tuinman','beveiliger','fotograaf','acteur']},
    {l:'Grieks eilandhotel', r:['receptionist','toerist','badmeester','schoonmaker','kok','barman','eigenaar','excursiegids']},
    {l:'Skigebied in Oostenrijk', r:['skiër','liftbediende','instructeur','pisteur','horecamedewerker','snowboarder','monteur','toerist']},
    {l:'Kerstmarkt in Duitsland', r:['glühweinverkoper','toerist','kraamhouder','muzikant','beveiliger','bakker','kind','marktmeester']},
    {l:'Wijnkelder in Frankrijk', r:['wijnmaker','proever','sommelier','toerist','oogstmedewerker','gids','importeur','keldermeester']},
    {l:'Vikingmuseum in Noorwegen', r:['gids','bezoeker','historicus','acteur','archeoloog','kind','conservator','fotograaf']},
    {l:'Strand in Barcelona', r:['toerist','strandverkoper','badmeester','surfer','politieagent','muzikant','fotograaf','hardloper']},
    {l:'Kanaal in Venetië', r:['gondelier','toerist','bewoner','fotograaf','hotelmedewerker','politieagent','kunstenaar','bootmonteur']},
    {l:'Sauna in Finland', r:['bezoeker','saunameester','receptionist','schoonmaker','toerist','sportteamlid','masseur','hotelgast']},
    {l:'Fado-café in Lissabon', r:['zanger','gitarist','gast','ober','toerist','eigenaar','kok','geluidstechnicus']},
    {l:'Kasteel aan de Loire', r:['gids','toerist','tuinman','conservator','historicus','schoonmaker','fotograaf','beheerder']},
    {l:'Tram in Praag', r:['passagier','bestuurder','controleur','toerist','student','forens','monteur','oudere reiziger']},
    {l:'Thermaalbad in Boedapest', r:['badgast','badmeester','toerist','masseur','receptionist','schoonmaker','arts','zwemmer']},
    {l:'Markt in Istanbul', r:['handelaar','toerist','theeverkoper','gids','juwelier','politieagent','taxichauffeur','lokale klant']},
    {l:'Fjordencruise', r:['kapitein','toerist','matroos','gids','fotograaf','kok','steward','natuurliefhebber']},
    {l:'Bierkelder in München', r:['ober','brouwer','toerist','muzikant','kok','vaste gast','eigenaar','afwasser']},
    {l:'Trein door Zwitserland', r:['conducteur','toerist','machinist','forens','skiër','servicemedewerker','zakenreiziger','fotograaf']},
    {l:'Archeologische site in Athene', r:['archeoloog','toerist','gids','bewaker','student','historicus','fotograaf','restaurator']},
    {l:'Ierse pub', r:['barman','muzikant','vaste gast','toerist','kok','eigenaar','serveerster','quizmaster']},
    {l:'Kroatische jachthaven', r:['zeiler','havenmeester','toerist','monteur','duiker','chartermedewerker','visser','receptionist']},
    {l:'Noorderlicht-lodge', r:['toerist','gids','fotograaf','receptionist','kok','chauffeur','wetenschapper','sneeuwscootergids']}
  ],
  world: [
    {l:'Safari-lodge in Kenia', r:['ranger','toerist','chauffeur','kok','fotograaf','bioloog','receptionist','gids']},
    {l:'Wolkenkrabber in New York', r:['kantoormedewerker','beveiliger','toerist','liftmonteur','directeur','schoonmaker','koerier','receptionist']},
    {l:'Sushi-bar in Tokio', r:['sushichef','gast','ober','toerist','visleverancier','afwasser','eigenaar','zakenman']},
    {l:'Outback-roadtrip in Australië', r:['reiziger','ranger','monteur','camperaar','fotograaf','truckchauffeur','gids','lokale bewoner']},
    {l:'Maya-tempel in Mexico', r:['archeoloog','toerist','gids','bewaker','fotograaf','historicus','verkoper','onderzoeker']},
    {l:'Theeplantage in Sri Lanka', r:['plukker','plantagebeheerder','toerist','chauffeur','theeproever','gids','exporteur','fotograaf']},
    {l:'Souk in Marrakech', r:['handelaar','toerist','leerbewerker','gids','theeverkoper','fotograaf','lokale klant','politieagent']},
    {l:'Cruiseschip in de Caraïben', r:['kapitein','passagier','steward','kok','entertainer','technicus','reisleider','barman']},
    {l:'National park in Canada', r:['ranger','wandelaar','kampeerder','fotograaf','bioloog','gids','visser','reddingswerker']},
    {l:'Koffieplantage in Colombia', r:['boer','plukker','brander','toerist','exporteur','gids','chauffeur','proever']},
    {l:'Woestijnkamp in Jordanië', r:['gids','reiziger','kok','chauffeur','fotograaf','kameelverzorger','kampbeheerder','archeoloog']},
    {l:'Metro in Seoul', r:['forens','student','toerist','machinist','controleur','monteur','verkoper','zakenreiziger']},
    {l:'Tempelcomplex in Thailand', r:['monnik','toerist','gids','fotograaf','bewaker','lokale bezoeker','verkoper','restaurator']},
    {l:'Onderzoeksstation op Antarctica', r:['wetenschapper','arts','kok','technicus','piloot','meteoroloog','monteur','onderzoeker']},
    {l:'Carnaval in Rio', r:['danser','muzikant','toerist','kostuummaker','beveiliger','fotograaf','verkoper','organisator']},
    {l:'Filmstudio in Hollywood', r:['acteur','regisseur','cameraman','geluidstechnicus','producent','grimeur','figurant','lichttechnicus']},
    {l:'Nachtmarkt in Taipei', r:['verkoper','toerist','kok','lokale klant','bezorger','fotograaf','marktmeester','student']},
    {l:'Duikboot bij koraalrif', r:['duiker','instructeur','kapitein','marien bioloog','toerist','monteur','fotograaf','bootsman']},
    {l:'Treinstation in India', r:['reiziger','conducteur','chai-verkoper','machinist','kruier','politieagent','toerist','kaartverkoper']},
    {l:'Wijnboerderij in Zuid-Afrika', r:['wijnmaker','proever','toerist','keldermeester','kok','gids','oogstmedewerker','sommelier']},
    {l:'Markt in Bangkok', r:['verkoper','toerist','kok','taxichauffeur','lokale klant','gids','fotograaf','politieagent']},
    {l:'Haven in Singapore', r:['havenarbeider','douanier','kapitein','kraanmachinist','planner','chauffeur','inspecteur','technicus']},
    {l:'Muziekfestival in Californië', r:['bezoeker','artiest','geluidstechnicus','beveiliger','foodtruckmedewerker','fotograaf','organisator','stagehand']},
    {l:'Bergdorp in Nepal', r:['sherpa','wandelaar','gids','theehuis-eigenaar','drager','fotograaf','monnik','reddingswerker']}
  ]
};

const QUESTION_IDEAS = [
  'Wat zou je hier absoluut niet vergeten mee te nemen?',
  'Hoe druk is het hier meestal?',
  'Wat is hier het meest irritante onderdeel van?',
  'Zou je hier graag een hele dag blijven?',
  'Welke kleding past hier het best?',
  'Wat hoor je hier waarschijnlijk vaak?',
  'Wat zou hier duur kunnen zijn?',
  'Ben je hier eerder voor plezier of voor werk?',
  'Wat zou je hier als eerste doen?',
  'Is dit eerder een plek voor overdag of ’s avonds?',
  'Met welk soort persoon kom je hier vaak?',
  'Wat zou hier een opvallende geur kunnen zijn?'
];
