function spEnemy(t,p){var path=map.roads[p%map.roads.length]||map.roads[0],st=at(path,0),e={t:t,path:path,q:0,x:st.x,y:st.y,z:0,ang:st.ang,hp:1,mh:1,speed:40,range:170,dmg:4,color:'#d4d0ba',score:5,reload:rnd(.3,.8),anim:0,dead:0,death:0,cover:0,building:0};if(t==='storm'){e.hp=e.mh=22;e.speed=48+rnd(-5,5);e.range=165;e.color='#b4c98b';e.score=6}else if(t==='truck'){e.hp=e.mh=70;e.speed=36;e.range=0;e.heavy=1;e.color='#a7b0a4';e.score=15;e.crew=5}else if(t==='technical'){e.hp=e.mh=90;e.speed=30;e.range=220;e.heavy=1;e.color='#9bb3a3';e.score=18;e.crew=4}else if(t==='halftrack'){e.hp=e.mh=120;e.speed=28;e.range=190;e.heavy=1;e.color='#9da894';e.score=24;e.crew=4}else if(t==='tank'){e.hp=e.mh=170;e.speed=22;e.range=240;e.heavy=1;e.color='#92a09b';e.score=35;e.crew=3}else if(t==='engineertruck'){e.hp=e.mh=85;e.speed=28;e.heavy=1;e.color='#a3a38a';e.score=20;e.crew=4;e.engineer=1}else if(t==='train'){e.hp=e.mh=210;e.speed=32;e.range=240;e.heavy=1;e.color='#989f9c';e.score=40;e.train=1;e.path=[{x:-.1,y:map.rail?map.rail.y:.32},{x:1.1,y:map.rail?map.rail.y:.32}];st=at(e.path,0);e.x=st.x;e.y=st.y;e.ang=0}S.enemies.push(e)}
function spPlane(){S.planes.push({x:-.1*W,y:H*(.14+rnd(-.04,.04)),v:W*.38,drop:0})} function spPara(x,y){S.enemies.push({t:'para',x:x,y:y,z:40+rnd(10,35),vz:18,ang:0,hp:20,mh:20,speed:34,range:175,dmg:4,color:'#d7d0b6',score:6,reload:rnd(.3,.8),anim:0,dead:0,death:0,para:1})} function spCiv(){var side=Math.random()<.5?-.08:1.08,t=side<0?1.08:-.08;S.civ.push({x:side*W,y:rnd(H*.40,H*.74),tx:t*W,v:rnd(28,45),alive:1,w:rnd(0,6.28),un:Math.random()<.18})}
function mkPlan(){var it=sc().plan(),t=.7,p=[];S.total=0;for(var i=0;i<it.length;i++)S.total+=it[i][0]==='plane'?it[i][1]*7:it[i][1];for(i=0;i<it.length;i++){for(var j=0;j<it[i][1];j++){p.push({t:t+rnd(0,.35),type:it[i][0],path:j%Math.max(1,map.roads.length)});t+=it[i][0]==='plane'?1.4:(/tank|train|halftrack|engineertruck/.test(it[i][0])?.65:.38)}}S.plan=p}
function upCharge(){var sec=hold.on?((performance.now()-hold.t0)/1000)*(1+.15*(S.charge-1)):0;$('chargeFill').style.width=(cl(sec/1,0,1)*100).toFixed(1)+'%';$('chargeText').textContent=sec<.25?'TAP':(sec<.68?'AP':'HE');$('chargeLabel').textContent='BURST x'+S.burst}
function ui(){$('level').textContent=S.level;$('sup').textContent=Math.floor(S.sup);$('hp').textContent=Math.max(0,Math.floor(S.hp));$('armor').textContent=Math.max(0,Math.floor(S.armor));$('hostiles').textContent=S.enemies.filter(function(e){return !e.dead}).length;$('progressFill').style.width=(Math.min(1,S.spawned/Math.max(1,S.total))*100).toFixed(1)+'%';$('hurt').style.opacity=S.red>0?cl(S.red,0,.5):0;upCharge()}
function show(id,t,sec){var e=$(id);e.textContent=t;e.style.opacity=1;clearTimeout(e._to);e._to=setTimeout(function(){e.style.opacity=0},(sec||1)*1000)}
function begin(){mkMap();varyMap();mkPlan();S.phase='play';S.enemies=[];S.shots=[];S.fx=[];S.smoke=[];S.fires=[];S.gore=[];S.debris=[];S.planes=[];S.civ=[];S.barrage=[];S.spawned=0;S.waveT=0;S.levelKills=0;S.combo=0;S.cooldown=0;$('startOverlay').classList.add('hidden');$('shopOverlay').classList.add('hidden');$('title').textContent='JBD // v6.4.1 // '+sc().name;$('scenarioName').textContent=sc().name;$('phaseLabel').textContent=S.level+'/9';show('banner',sc().name,1);for(var i=0;i<14+S.level*2;i++)S.barrage.push({t:rnd(.18,2.6),x:rnd(.05,.95)*W,y:rnd(.08,.84)*H,p:rnd(32,62),warn:rnd(.10,.22)});show('banner','ARTILLERY INCOMING',1.2);ui()}
function brief(){$('startTitle').textContent=sc().name;$('startText').textContent=sc().desc+' Tik is MG burst, half-seconde is AP, lang is HE met splash en brand. Elk level opent met artillerie.';$('startOverlay').classList.remove('hidden');S.phase='brief'}
function shop(){S.phase='shop';$('shopTitle').textContent='LEVEL CLEAR';$('shopText').textContent='Supply: '+S.sup+' · Kills: '+S.levelKills+' · Kies upgrades.';$('uCal').textContent=S.caliber;$('uBurst').textContent=S.burst;$('uCharge').textContent=S.charge;$('uBlast').textContent=S.blast;$('uReload').textContent=S.reload;$('shopOverlay').classList.remove('hidden')}
function buy(k){var cost={caliber:12+S.caliber*4,burst:10+S.burst*4,charge:10+S.charge*4,blast:12+S.blast*4,reload:11+S.reload*4,repair:8,armor:8}[k];if(S.sup<cost)return;S.sup-=cost;if(k==='caliber')S.caliber++;if(k==='burst')S.burst=Math.min(5,S.burst+1);if(k==='charge')S.charge++;if(k==='blast')S.blast++;if(k==='reload')S.reload++;if(k==='repair')S.hp=Math.min(S.maxHp,S.hp+35);if(k==='armor')S.armor+=20;aud('hit');shop();ui()}
function fire(x,y,k){if(S.phase!=='play'||S.cooldown>0)return;var b=bunk(),i;if(k==='he'){S.shots.push({k:'he',x:b.x,y:b.y-16,tx:x,ty:y,t:0,speed:1.05+.15*S.reload});S.cooldown=Math.max(.16,.44-.03*S.reload);aud('he');return}var count=k==='mg'?S.burst:1,spread=k==='mg'?0.028:.012;for(i=0;i<count;i++){var ox=(i-(count-1)/2)*6,sx=b.x+ox,sy=b.y-20,tx=x+rnd(-spread*W,spread*W),ty=y+rnd(-spread*H,spread*H),dx=tx-sx,dy=ty-sy,len=Math.sqrt(dx*dx+dy*dy)||1;S.shots.push({k:k,x:sx,y:sy,dx:dx/len,dy:dy/len,v:(k==='mg'?820:760)+(S.reload*35),t:(k==='mg'?.44:.55)})}S.cooldown=k==='mg'?Math.max(.05,.20-.015*S.reload):Math.max(.13,.32-.015*S.reload);aud(k==='mg'?'mg':'ap')