function mkPhase(index,name,threshold=4){return{phase:true,index,name,threshold}}
function buildWave(n){const q=[],lane=()=>rnd(-40,40),inf=Math.min(15,5+n*2);q.push(mkPhase(1,'WIDE SPEARHEAD',3));q.push({type:n%3===0?'tank':'stug',lane:lane()});q.push({type:'technical',lane:lane()});for(let i=0;i<Math.max(4,inf-2);i++)q.push({type:i%5===0?'storm':'rifle',lane:lane(),follow:true});if(n>=2)q.push({type:'motorcycle',lane:lane()});q.push(mkPhase(2,'TWIN-BRIDGE CONVOY',4));q.push({type:'truck',lane:lane()});if(n>=2)q.push({type:'halftrack',lane:lane()});for(let i=0;i<Math.min(5,n+1);i++)q.push({type:i%3===0?'mg':'rifle',lane:lane(),follow:true});q.push(mkPhase(3,'RIVER FORTIFY',5));q.push({type:'engineertruck',lane:lane()});q.push({type:'motorcycle',lane:lane()});q.push({type:'motorcycle',lane:lane()});q.push({type:'grenadier',lane:lane()});if(n>=3)q.push({type:'apc',lane:lane()});if(n>=4)q.push({type:'mg',lane:lane()});return q}
function previewWave(n){const q=buildWave(n);return{inf:q.filter(x=>x.type&&['rifle','storm','mg','grenadier'].includes(x.type)).length+10,armor:q.filter(x=>x.type&&DEF[x.type]?.vehicle).length,eng:2}}
function startWave(){if(state.phase==='wave')return;state.wave++;state.phase='wave';state.phaseIndex=0;state.waveKills=0;state.waveBounty=0;state.queue=buildWave(state.wave);state.spawnClock=.2;state.chain=0;state.chainClock=0;$('brief').style.display='none';$('shop').style.display='none';$('msg').textContent=`WAVE ${state.wave} // contact`;updateUI()}
function spawn(type,lane=0,opts={}){const d=DEF[type],spread=d.vehicle?9.5:13.5,e={id:++state.id,type,a:rnd(-101,-91),s:clamp(lane+rnd(-spread,spread),-46,46),hp:d.hp,maxhp:d.hp,speed:d.speed,engage:d.engage,reload:d.reload,fireClock:rnd(.2,.8),mode:'move',moveClock:rnd(.8,1.7),stance:'stand',walk:Math.random()*6,age:0,action:'',actionT:0,actionCooldown:rnd(.8,2.1),followId:null,slot:opts.slot??Math.floor(rnd(-2,3)),digClock:rnd(11,17),dugIn:false,inTrench:false,buildState:null,unloaded:false,retreat:false,kind:d.kind,vehicle:!!d.vehicle,heavy:!!d.heavy,fort:!!d.fort,rewarded:false,damage:d.damage,bridgeS:null,swimming:false,wasSwimming:false,swimSoundT:rnd(.1,.5)};if(e.vehicle)chooseBridge(e);state.enemies.push(e);return e}
function assignFollowers(){const vehicles=state.enemies.filter(e=>e.vehicle&&!e.retreat&&e.type!=='motorcycle');for(const e of state.enemies){if(!['rifle','storm','mg','grenadier'].includes(e.type)||e.followId)continue;let best=null,bestScore=1e9;for(const v of vehicles){const da=v.a-e.a,ds=Math.abs(v.s-e.s);if(da>-8&&da<42&&ds<34){let bias=v.type==='stug'||v.type==='tank'?-15:v.type==='technical'?-8:v.type==='truck'?-4:0;const sc=da+ds*.6+bias;if(sc<bestScore){bestScore=sc;best=v}}}if(best)e.followId=best.id}}
function unloadVehicle(e){if(e.unloaded)return;e.unloaded=true;const count=DEF[e.type].passengers||0;for(let i=0;i<count;i++){const type=e.type==='engineertruck'?'engineer':(i%6===0?'mg':i%5===0?'storm':'rifle');const n=spawn(type,e.s+(i-(count-1)/2)*2.4,{slot:i%5-2});n.a=e.a-rnd(2,6);n.followId=e.type==='engineertruck'?null:e.id;if(type==='engineer'){n.buildState='seek';n.digClock=99}}e.retreat=true;e.mode='move';floater(e.a,e.s,e.type==='engineertruck'?'ENGINEERS OUT':'TROOPS OUT',C.gold)}
function spawnFromQueue(spec){const e=spawn(spec.type,spec.lane||0);if(spec.follow)setTimeout(()=>assignFollowers(),0);return e}

// ---------- AI ----------
