const TRENCHES=[{a:-2,s:-38,w:11},{a:8,s:33,w:12},{a:27,s:-21,w:13},{a:41,s:18,w:12}];
function nearestVehicle(e){return state.enemies.find(v=>v.id===e.followId&&v.hp>0&&!v.retreat)}
function movementTarget(e){const v=nearestVehicle(e);if(v){const back=e.type==='mg'?9:7.5,side=(e.slot||0)*3.2;return{a:v.a-back,s:v.s+side,vehicle:v}}const rt=riverTarget(e,true);if(rt)return rt;return{a:77,s:clamp(e.s*.82,-38,38),vehicle:null}}
function maybeEnterTrench(e){if(e.vehicle||e.fort||e.dugIn||e.inTrench||e.type==='engineer')return false;for(const t of TRENCHES){if(Math.abs(e.a-t.a)<2.2&&Math.abs(e.s-t.s)<t.w*.55&&Math.random()<.065){e.inTrench=true;e.trenchT=rnd(3.2,5.7);e.stance='crouch';e.action='drop';e.actionT=.42;floater(e.a,e.s,'IN COVER',C.gold);return true}}return false}
function initInfantryAnim(e){if(e.vehicle||e.fort||e.magSize)return;const m={rifle:5,storm:6,mg:8,grenadier:2,engineer:5};e.magSize=m[e.type]||5;e.mag=e.magSize;e.reloadT=0;e.recoilT=0;e.swimKick=0}
function beginReload(e){if(e.vehicle||e.fort||e.reloadT>0)return;e.reloadT=e.type==='mg'?1.32:e.type==='grenadier'?1.55:rnd(.82,1.08);e.action='reload';e.actionT=e.reloadT;e.mode='fire'}
function updateEngineer(e,dt){if(e.type!=='engineer')return false;if(e.buildState==='seek'){const site={a:34,s:clamp(e.s+rnd(-6,6),-32,32)};const da=site.a-e.a,ds=site.s-e.s,d=Math.hypot(da,ds);if(d>1.6){e.a+=da/d*e.speed*1.2*dt;e.s+=ds/d*e.speed*1.2*dt;e.walk+=dt*9;e.action='sprint';return true}e.buildState='build';e.buildT=0;e.action='build';floater(e.a,e.s,'BUILDING',C.gold);return true}if(e.buildState==='build'){e.buildT+=dt;e.action='build';if(Math.random()<dt*.65)state.fx.push({kind:'dust',a:e.a+rnd(-1,1),s:e.s+rnd(-1,1),t:0,life:.45});if(e.buildT>=4.4){const b=spawn('fieldbunker',e.s);b.a=e.a;b.s=e.s;b.complete=true;e.buildState='done';e.mode='fire';floater(e.a,e.s,'BUNKER ONLINE',C.red);boom(false)}return true}return false}
function updateEnemy(e,dt){e.age+=dt;initInfantryAnim(e);e.actionCooldown-=dt;if(e.recoilT>0)e.recoilT-=dt;if(e.actionT>0)e.actionT-=dt;else if(e.action!=='build'){if(e.action==='duck'||e.action==='kneel')e.stance='stand';e.action=''};
  if(e.reloadT>0){e.reloadT-=dt;e.action='reload';e.actionT=.12;e.walk+=dt*3;if(e.reloadT<=0){e.mag=e.magSize;e.action='rack';e.actionT=.24}return}
  if(e.fort){e.fireClock-=dt;if(e.fireClock<=0){enemyFire(e);e.fireClock=.72}return}
  if(e.type==='engineer'&&updateEngineer(e,dt))return;
  if(e.inTrench){e.trenchT-=dt;e.fireClock-=dt;if(e.fireClock<=0&&Math.abs(77-e.a)<e.engage){enemyFire(e);e.fireClock=e.reload*1.05}if(e.trenchT<=0){e.inTrench=false;e.stance='stand';e.action='climb';e.actionT=.35}return}
  if(e.vehicle&&['truck','engineertruck'].includes(e.type)&&!e.unloaded&&e.a>18){unloadVehicle(e);return}
  if(e.retreat){const rt=riverTarget(e,false),t=rt||{a:-104,s:e.s},da=t.a-e.a,ds=t.s-e.s,d=Math.max(.001,Math.hypot(da,ds));e.a+=da/d*e.speed*1.52*dt;e.s+=ds/d*e.speed*1.52*dt;if(e.a<-102)e.hp=0;return}
  if(maybeEnterTrench(e))return;
  if(!e.vehicle&&!e.dugIn&&e.type!=='engineer'&&e.a>8){e.digClock-=dt;if(e.digClock<=0){e.dugIn=true;e.stance='crouch';e.mode='fire';e.action='drop';e.actionT=.35;floater(e.a,e.s,'DUG IN → HE',C.gold);return}}
  const bunker={a:77,s:0};const range=Math.hypot(bunker.a-e.a,bunker.s-e.s);e.fireClock-=dt;e.moveClock-=dt;
  if(e.mode==='fire'){
    if(e.fireClock<=0&&range<e.engage){enemyFire(e);e.fireClock=e.reload*rnd(.86,1.08)}
    if(e.moveClock<=0&&e.reloadT<=0){e.mode='move';e.moveClock=rnd(.62,1.25)}
  }else{
    const t=movementTarget(e),da=t.a-e.a,ds=t.s-e.s,d=Math.max(.001,Math.hypot(da,ds));let speed=e.speed*(e.vehicle?1.09:1.08);if(t.vehicle){const gap=t.vehicle.a-e.a;if(gap>12)speed=Math.max(speed,t.vehicle.speed*1.6);else speed=t.vehicle.speed*rnd(.96,1.06)}if(e.action==='sprint')speed*=1.30;const willSwim=!e.vehicle&&!t.vehicle&&inRiver(e.a,e.s)&&!nearBridge(e.s);e.swimming=willSwim;if(e.swimming)speed*=.57;if(e.swimming!==e.wasSwimming){state.fx.push({kind:'splash',a:e.a,s:e.s,t:0,life:.5});sample('splash',.17,rnd(.9,1.1),clamp((isoAS(e.a,e.s).x/W)*2-1,-.8,.8));e.wasSwimming=e.swimming}if(e.swimming){e.swimKick=(e.swimKick||0)+dt*11;e.swimSoundT-=dt;if(e.swimSoundT<=0){sample('swim',.065,rnd(.86,1.12),clamp((isoAS(e.a,e.s).x/W)*2-1,-.8,.8));e.swimSoundT=rnd(.42,.68)}}e.a+=da/d*speed*dt;e.s+=ds/d*speed*dt;e.walk+=dt*(e.swimming?9.5:(5.7+speed*1.35));if(range<e.engage&&e.moveClock<=0&&!e.swimming){e.mode='fire';e.moveClock=rnd(.42,.9);e.action='aim';e.actionT=.28}}
  if(!e.vehicle&&e.actionCooldown<=0&&!e.swimming&&e.reloadT<=0){const r=Math.random();if(r<.18){e.action='look';e.actionT=rnd(.28,.55)}else if(r<.34){e.action='point';e.actionT=rnd(.32,.55)}else if(r<.49){e.action='signal';e.actionT=rnd(.35,.62)}else if(r<.64){e.action='duck';e.actionT=rnd(.28,.5);e.stance='crouch'}else if(r<.80){e.action='kneel';e.actionT=rnd(.32,.58);e.stance='crouch'}else{e.action='sprint';e.actionT=rnd(.42,.78)}e.actionCooldown=rnd(.8,2.35)}
  if(e.a>82){damageBunker(e.heavy?16:e.vehicle?9:5);e.hp=0}
}
function enemyFire(e){if(!e.vehicle&&!e.fort){initInfantryAnim(e);if(e.mag<=0){beginReload(e);return}e.mag--;e.recoilT=.13;e.action='fire';e.actionT=.16;if(e.mag<=0)setTimeout(()=>{if(e.hp>0&&!e.vehicle&&!e.fort)beginReload(e)},90)}const bunker={a:77,s:0};const acc=(e.type==='tank'||e.type==='stug') ? .68 : (e.type==='mg'||e.type==='fieldbunker') ? .42 : .36;const hit=Math.random()<acc;state.shots.push({enemy:true,a:e.a,s:e.s,ta:bunker.a,ts:bunker.s,t:0,life:e.heavy?.45:.28,hit,damage:e.damage});enemySound(e);state.fx.push({kind:'muzzle',a:e.a,s:e.s,t:0,life:.10})}
function damageBunker(dmg){if(state.armor>0){const a=Math.min(state.armor,dmg*.7);state.armor-=a;dmg-=a}state.hp-=dmg;state.shake=Math.min(8,state.shake+dmg*.35);if(state.hp<=0){state.hp=0;state.phase='gameover';$('msg').textContent='BUNKER LOST // refresh om opnieuw te spelen'}}

// ---------- PLAYER COMBAT ----------
