function weaponStats(type){const dmg=1+(state.damageLvl-1)*.15;if(type==='mg')return{cycle:.58,heat:18,damage:17*dmg,range:162,burst:4};if(type==='ap')return{cycle:1.28,heat:10,damage:92*dmg,range:176,burst:1};return{cycle:2.45,heat:7,damage:98*dmg,range:155,splash:9.5,burst:1}}
function fire(){if(state.phase!=='wave'||state.overheated)return;const w=weaponStats(selected);if(state.ammo[selected]<=0){$('msg').textContent=`${selected.toUpperCase()} EMPTY`;return}state.ammo[selected]--;state.heat+=w.heat;if(state.heat>100+(state.coolLvl-1)*18){state.overheated=true;$('msg').textContent='OVERHEAT'}shotSound(selected);state.shake=Math.min(5,state.shake+(selected==='mg'?.6:selected==='ap'?1.8:2.4));const b={a:77,s:0},aim=asFromScreen(mouse.x,mouse.y),da=aim.a-b.a,ds=aim.s-b.s,len=Math.max(.01,Math.hypot(da,ds)),na=da/len,ns=ds/len;if(selected==='he'){const d=Math.min(w.range,len),ta=b.a+na*d,ts=b.s+ns*d;state.shots.push({enemy:false,type:'he',a:b.a,s:b.s,ta,ts,t:0,life:.78,damage:w.damage,splash:w.splash,arc:true});for(const e of state.enemies){if(!e.vehicle&&!e.fort&&Math.hypot(e.a-ta,e.s-ts)<w.splash*1.7&&Math.random()<.7){e.action='sprint';e.actionT=.9;e.s+=rnd(-4,4)}}}else{for(let i=0;i<w.burst;i++){const spread=selected==='mg'&&i?rnd(-.018,.018):0,ang=Math.atan2(ns,na)+spread,ra=Math.cos(ang),rs=Math.sin(ang);state.shots.push({enemy:false,type:selected,a:b.a,s:b.s,ta:b.a+ra*w.range,ts:b.s+rs*w.range,t:-i*(selected==='mg'?.075:0),life:selected==='mg'?.33:.25,damage:w.damage,hitDone:false})}}state.trigger=w.cycle;updateUI()}
function hitRadius(e){if(e.fort)return 4.8;if(e.heavy)return 4.0;if(e.vehicle)return e.type==='motorcycle'?2.0:3.2;return e.dugIn||e.inTrench?1.5:2.1}
function segmentHit(a1,s1,a2,s2,e){const A=isoAS(a1,s1),B=isoAS(a2,s2),P=isoAS(e.a,e.s),r=e.fort?18:e.heavy?16:e.vehicle?13:(e.dugIn||e.inTrench?8:10);const dx=B.x-A.x,dy=B.y-A.y,l2=dx*dx+dy*dy;if(l2<.001)return null;const t=clamp(((P.x-A.x)*dx+(P.y-A.y)*dy)/l2,0,1);const qx=A.x+dx*t,qy=A.y+dy*t;if(Math.hypot(P.x-qx,P.y-qy)<=r)return t;return null}
function damageEnemy(e,ammo,base,impactA=e.a,impactS=e.s){if(e.hp<=0)return;const clsBefore=targetClass(e),eff=effectiveness(ammo,e);let dmg=base*eff*rnd(.9,1.08);if((e.dugIn||e.inTrench)&&ammo==='he')dmg*=1.15;if(e.heavy&&ammo==='ap'&&Math.random()<.12){dmg*=2.1;floater(e.a,e.s,'CRITICAL',C.gold)}e.hp-=dmg;floater(e.a,e.s,Math.round(dmg),AMMOCOL[ammo]);if(!e.vehicle&&!e.fort&&ammo==='mg'&&Math.random()<.45){e.action='duck';e.actionT=.5;e.stance='crouch'}if(e.hp<=0)killEnemy(e,ammo,clsBefore)}
function killEnemy(e,ammo,clsBefore){if(e.hp<-999)return;e.hp=-1000;const originalClass=targetClass(e);if(clsBefore)e._rewardClass=clsBefore;award(e,ammo);if(e.vehicle){state.fx.push({kind:'explosion',a:e.a,s:e.s,t:0,life:.7,big:e.heavy});boom(e.heavy);if(['truck','engineertruck','halftrack','apc'].includes(e.type)&&!e.unloaded)unloadVehicle(e)}else if(e.fort){state.fx.push({kind:'explosion',a:e.a,s:e.s,t:0,life:.6,big:true});boom(true)}else{state.corpses.push({type:e.type,a:e.a,s:e.s,t:0,life:5.2,dir:Math.random()<.5?-1:1,walk:e.walk});noise(.045,.018)}state.waveKills++}
function updateShot(sh,dt){sh.t+=dt;if(sh.t<0)return;if(sh.enemy){const u=clamp(sh.t/sh.life,0,1);if(u>=1&&!sh.done){if(sh.hit)damageBunker(sh.damage);else if(Math.random()<.22){state.fx.push({kind:'dust',a:77+rnd(-3,3),s:rnd(-5,5),t:0,life:.35})}sh.done=true}return}const u=clamp(sh.t/sh.life,0,1),q=1-Math.pow(1-u,1.35),ca=lerp(sh.a,sh.ta,q),cs=lerp(sh.s,sh.ts,q);sh.ca=ca;sh.cs=cs;if(sh.type==='he'){if(u>=1&&!sh.done){state.craters.push({a:sh.ta,s:sh.ts,r:rnd(4.5,6.5),t:0});for(const e of state.enemies){if(e.hp>0){const d=Math.hypot(e.a-sh.ta,e.s-sh.ts);if(d<sh.splash+hitRadius(e)){const fall=clamp(1-d/(sh.splash+hitRadius(e)),.25,1);damageEnemy(e,'he',sh.damage*fall,sh.ta,sh.ts)}}}state.fx.push({kind:'explosion',a:sh.ta,s:sh.ts,t:0,life:.7,big:true});boom(true);sh.done=true}return}
  if(!sh.hitDone){let best=null;for(const e of state.enemies){if(e.hp<=0)continue;const t=segmentHit(sh.a,sh.s,ca,cs,e);if(t!==null&&(!best||t<best.t))best={e,t}}if(best){damageEnemy(best.e,sh.type,sh.damage);sh.hitDone=true;sh.done=true;state.fx.push({kind:sh.type==='ap'?'spark':'dust',a:best.e.a,s:best.e.s,t:0,life:.28});return}}
  if(u>=1)sh.done=true
}

// ---------- DRAW WORLD ----------
