function showPanel(el){if(!el)return;el.hidden=false;el.style.display='block'}
function hidePanel(el){if(!el)return;el.hidden=true;el.style.display='none'}
function finishWave(){state.phase='shop';const bonus=18+state.wave*9;state.supply+=bonus;state.ammo.mg+=20;state.ammo.ap+=3;state.ammo.he+=2;showPanel($('shop'));$('msg').textContent=`WAVE CLEAR · +${bonus} SUP · kill bounty ${state.waveBounty}`;updateUI()}
function update(dt){state.shake=Math.max(0,state.shake-dt*8);state.engineT-=dt;if(state.phase==='wave'&&state.engineT<=0){const movers=state.enemies.filter(e=>e.hp>0&&e.vehicle&&!e.fort&&!e.retreat);if(movers.length){const e=movers[Math.floor(Math.random()*movers.length)],pan=clamp((isoAS(e.a,e.s).x/W)*2-1,-.8,.8);sample(e.heavy?'track':'engine',e.heavy?.10:.07,rnd(.84,1.12),pan)}state.engineT=rnd(.30,.52)}state.heat=Math.max(0,state.heat-dt*(23+(state.coolLvl-1)*5));if(state.overheated&&state.heat<42){state.overheated=false;$('msg').textContent='READY'}state.trigger-=dt;if(state.chainClock>0){state.chainClock-=dt;if(state.chainClock<=0)state.chain=0}if(fireHeld&&state.trigger<=0)fire();for(const sh of state.shots)updateShot(sh,dt);state.shots=state.shots.filter(sh=>!sh.done);for(const f of state.fx)f.t+=dt;state.fx=state.fx.filter(f=>f.t<f.life).slice(-54);for(const c of state.corpses)c.t+=dt;state.corpses=state.corpses.filter(c=>c.t<c.life).slice(-16);if(state.phase==='wave'){state.spawnClock-=dt;if(state.queue.length&&state.spawnClock<=0){const alive=state.enemies.filter(e=>e.hp>0).length;const next=state.queue[0];if(next.phase){if(alive<=next.threshold){state.queue.shift();state.phaseIndex=next.index;state.phaseName=next.name;state.spawnClock=1.0;$('msg').textContent=`PHASE ${next.index} · ${next.name}`;uiSound()}else state.spawnClock=.22}else if(alive<15){state.queue.shift();spawnFromQueue(next);state.spawnClock=next.type==='motorcycle'?.16:next.type.includes('truck')?.44:.26}else state.spawnClock=.12}assignFollowers();for(const e of state.enemies)if(e.hp>0)updateEnemy(e,dt);state.enemies=state.enemies.filter(e=>e.hp>-500);if(!state.queue.length&&!state.enemies.some(e=>e.hp>0)){state.phase='ending';setTimeout(()=>{if(state.phase==='ending')finishWave()},350)}}updateUI()}
function updateUI(){$('wave').textContent=state.wave;$('supply').textContent=state.supply;$('hp').textContent=Math.round(state.hp);$('armor').textContent=Math.round(state.armor);$('hostiles').textContent=state.enemies.filter(e=>e.hp>0).length+state.queue.filter(x=>!x.phase).length;$('phase').textContent=state.phase==='wave'?`${state.phaseIndex}/3`:'–';$('chain').textContent=`COUNTER CHAIN ×${state.chain}`;$('amg').textContent=state.ammo.mg;$('aap').textContent=state.ammo.ap;$('ahe').textContent=state.ammo.he;$('heat').style.width=Math.min(100,state.heat/(100+(state.coolLvl-1)*18)*100)+'%';$('dmgLvl').textContent=state.damageLvl;$('coolLvl').textContent=state.coolLvl;document.querySelectorAll('[data-ammo]').forEach(b=>b.classList.toggle('active',b.dataset.ammo===selected));document.querySelectorAll('[data-buy]').forEach(b=>{const k=b.dataset.buy,c={mg:12,ap:14,he:18,repair:14,armor:16,damage:22,cool:18}[k];b.disabled=state.supply<c})}
function aimFromPointer(e){const r=canvas.getBoundingClientRect();mouse.x=clamp(e.clientX-r.left,0,r.width);mouse.y=clamp(e.clientY-r.top,0,r.height)}
canvas.addEventListener('pointermove',e=>{aimFromPointer(e);if(e.pointerType==='touch')e.preventDefault()},{passive:false});
canvas.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch'&&e.button!==0)return;aimFromPointer(e);e.preventDefault();try{canvas.setPointerCapture(e.pointerId)}catch(_){ }fireHeld=true;if(state.trigger<=0)fire()},{passive:false});
const stopFire=e=>{fireHeld=false;if(e&&e.pointerId!==undefined){try{canvas.releasePointerCapture(e.pointerId)}catch(_){}}};
canvas.addEventListener('pointerup',stopFire,{passive:false});canvas.addEventListener('pointercancel',stopFire,{passive:false});addEventListener('pointerup',stopFire);canvas.addEventListener('contextmenu',e=>e.preventDefault());
addEventListener('keydown',e=>{if(e.key==='1')selected='mg';if(e.key==='2')selected='ap';if(e.key==='3')selected='he';updateUI()});document.querySelectorAll('[data-ammo]').forEach(b=>b.onclick=()=>{selected=b.dataset.ammo;uiSound();updateUI()});
function openBrief(){const n=state.wave+1,p=previewWave(n);$('bw').textContent=n;$('bi').textContent=p.inf;$('ba').textContent=p.armor;$('be').textContent=p.eng;showPanel($('brief'))}
$('briefBtn').onclick=openBrief;
const deployNow=e=>{if(e){e.preventDefault();e.stopPropagation()}hidePanel($('brief'));startWave()};
$('goBtn').addEventListener('pointerup',deployNow,{passive:false});
$('goBtn').addEventListener('click',deployNow);
$('nextBtn').onclick=()=>{hidePanel($('shop'));openBrief()};
document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{const k=b.dataset.buy,c={mg:12,ap:14,he:18,repair:14,armor:16,damage:22,cool:18}[k];if(state.supply<c)return;state.supply-=c;if(k==='mg')state.ammo.mg+=35;if(k==='ap')state.ammo.ap+=8;if(k==='he')state.ammo.he+=5;if(k==='repair')state.hp=Math.min(state.maxhp,state.hp+45);if(k==='armor')state.armor+=25;if(k==='damage')state.damageLvl++;if(k==='cool')state.coolLvl++;uiSound();updateUI()});
function loop(t){const dt=Math.min(.035,(t-last)/1000);last=t;update(dt);draw();requestAnimationFrame(loop)}updateUI();if(PORTRAIT){$('msg').textContent='TIK = VUUR · VASTHOUDEN = MG BURST · ammo onderin'}openBrief();requestAnimationFrame(loop);
window.__JBD={state,startWave,spawn,fire};
