const $=s=>document.querySelector(s);
const screens=['setup','briefing','handoff','evidence','discuss','accuse','result'];
let players=['Eline','Maarten','Juan','Daniëlle'];
let selectedCase='demo';
let game=null;
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function show(id){screens.forEach(x=>$('#'+x).classList.toggle('hidden',x!==id));$('#homeBtn').classList.toggle('hidden',id==='setup');scrollTo(0,0)}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1600)}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function save(){try{localStorage.setItem('molePlayers',JSON.stringify(players));localStorage.setItem('moleCase',selectedCase)}catch(e){}}
function load(){try{const p=JSON.parse(localStorage.getItem('molePlayers'));if(Array.isArray(p)&&p.length===4)players=p;const c=localStorage.getItem('moleCase');if(CASES.some(x=>x.id===c))selectedCase=c}catch(e){}}
function renderPlayers(){const p=$('#players');p.innerHTML='';players.forEach((name,i)=>{const row=document.createElement('div');row.className='player';row.innerHTML=`<div class="num">${i+1}</div><input maxlength="20" value="${esc(name)}" aria-label="Speler ${i+1}">`;const inp=row.querySelector('input');inp.oninput=()=>{players[i]=inp.value;save()};p.appendChild(row)})}
function renderCases(){const g=$('#caseGrid');g.innerHTML='';CASES.forEach(c=>{const b=document.createElement('button');b.type='button';b.className='casebtn '+(c.demo?'demo ':'')+(selectedCase===c.id?'active':'');b.innerHTML=`<b>${c.demo?'🎓 ':''}${esc(c.title)}</b><span>${esc(c.tag)}</span>`;b.onclick=()=>{selectedCase=c.id;renderCases();save()};g.appendChild(b)})}
function cleanNames(){players=players.map((x,i)=>x.trim()||`Speler ${i+1}`);if(new Set(players.map(x=>x.toLowerCase())).size!==4){toast('Gebruik vier verschillende namen');return false}return true}
function startGame(){if(!cleanNames())return;const c=CASES.find(x=>x.id===selectedCase)||CASES[0];const roleOrder=shuffle(ROLE_KEYS);const moleIndex=Math.floor(Math.random()*4);game={case:c,round:0,pass:0,moleIndex,assignments:players.map((name,i)=>({name,role:roleOrder[i]}))};save();renderBriefing();show('briefing')}
function renderBriefing(){const c=game.case;$('#caseTitle').textContent=c.title;$('#caseIntro').textContent=c.intro;$('#suspectList').innerHTML=c.suspects.map(s=>`<div class="suspect"><div class="sid">${s[0]}</div><div><b>${esc(s[1])}</b><div>${esc(s[2])}</div></div></div>`).join('')}
function startEvidenceRound(){game.pass=0;showHandoff()}
function showHandoff(){const p=game.assignments[game.pass];$('#handoffName').textContent=p.name;$('#readyName').textContent=p.name;show('handoff')}
function revealEvidence(){const p=game.assignments[game.pass];const role=ROLES[p.role];$('#roleBadge').textContent=`${role.icon} ${role.name}`;$('#evidenceName').textContent=p.name;const isMole=game.pass===game.moleIndex;$('#moleBox').classList.toggle('hidden',!isMole);if(isMole){const culprit=game.case.suspects.find(s=>s[0]===game.case.culprit);$('#moleText').innerHTML=`Bescherm <b>${esc(culprit[0]+' — '+culprit[1])}</b>. Je mag bewijs bagatelliseren, informatie weglaten en een andere theorie verdedigen. <b>Verzin geen nieuwe feiten.</b>`}const fact=game.case.clues[p.role][game.round];$('#facts').innerHTML=`<div class="fact"><b>BEWIJSRONDE ${game.round+1}</b>${esc(fact)}</div>`;show('evidence')}
function nextPass(){game.pass++;if(game.pass<4)showHandoff();else showDiscussion()}
function showDiscussion(){const r=game.round+1;$('#roundTitle').textContent=`Bespreek ronde ${r}`;$('#roundLead').textContent=r===1?'Leg de eerste tijdlijn en motieven naast elkaar. Trek nog geen snelle conclusie.':r===2?'Zoek vooral naar botsingen tussen alibi, toegang en fysiek bewijs.':'Dit is de doorbraakronde. Welke verdachte blijft overeind als álle feiten tegelijk waar zijn?';const tip=$('#demoTip');if(game.case.demo){tip.classList.remove('hidden');tip.textContent=game.case.tips[game.round]}else tip.classList.add('hidden');$('#nextRoundBtn').textContent=game.round<2?`Nieuwe bewijsronde ${game.round+2} →`:'Naar eindconclusie →';show('discuss')}
function nextRound(){if(game.round<2){game.round++;startEvidenceRound()}else showAccuse()}
function showAccuse(){const c=game.case;$('#culpritSelect').innerHTML='<option value="">Kies verdachte…</option>'+c.suspects.map(s=>`<option value="${s[0]}">${s[0]} — ${esc(s[1])}</option>`).join('');$('#moleSelect').innerHTML='<option value="">Kies speler…</option>'+game.assignments.map((p,i)=>`<option value="${i}">${esc(p.name)}</option>`).join('');show('accuse')}
function revealResult(){const chosenC=$('#culpritSelect').value,chosenM=$('#moleSelect').value;if(!chosenC||chosenM===''){toast('Kies zowel een dader als een mol');return}const culprit=game.case.suspects.find(s=>s[0]===game.case.culprit);const mole=game.assignments[game.moleIndex];const caseRight=chosenC===game.case.culprit,moleRight=+chosenM===game.moleIndex;$('#resultTitle').textContent=caseRight?'Dader gevonden':'De dader ontsnapt';const co=$('#caseOutcome');co.className='resultbox '+(caseRight?'good':'bad');co.innerHTML=`<b>${caseRight?'✓ Zaak opgelost':'✕ Verkeerde arrestatie'}</b><div class="muted" style="margin-top:4px">De echte dader was <b>${esc(culprit[0]+' — '+culprit[1])}</b>.</div>`;const mo=$('#moleOutcome');mo.className='resultbox '+(moleRight?'good':'bad');mo.innerHTML=`<b>${moleRight?'✓ Mol ontmaskerd':'✕ Mol bleef onder de radar'}</b><div class="muted" style="margin-top:4px">De mol was <b>${esc(mole.name)}</b> (${ROLES[mole.role].name}).</div>`;$('#solution').textContent=game.case.solution;show('result')}
$('#startBtn').onclick=startGame;$('#beginRoundBtn').onclick=startEvidenceRound;$('#readyBtn').onclick=revealEvidence;$('#seenBtn').onclick=nextPass;$('#nextRoundBtn').onclick=nextRound;$('#revealResultBtn').onclick=revealResult;$('#againBtn').onclick=()=>show('setup');$('#homeBtn').onclick=()=>{if(confirm('Huidige zaak stoppen?'))show('setup')};
if('serviceWorker'in navigator&&location.protocol==='https:')addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
load();renderPlayers();renderCases();
