/* JBD v6.11 — clean HUD, gentle efficiency, upgrades after every level */
(()=>{
  const wait=()=>{const J=window.JBD;if(!J||!J.Render||!J.Progress||!J.Scenarios||!J.U||!J.CONFIG){setTimeout(wait,35);return;}if(J.__v611Hud)return;J.__v611Hud=true;
    const U=J.U,state=()=>window.__JBD_STATE__||null;
    function kills(s){return (s.stats?.kills||0)+(s.stats?.vehicleKills||0)+(s.stats?.airKills||0)+(s.stats?.artilleryKills||0);}
    function resetEff(s){if(!s)return;s._v611Eff=.75;s._v611EffSeed=s.scenario?.seed??0;s._v611EffLast={tr:s.stats?.triggers||0,ok:s.stats?.effectiveTriggers||0,h:s.stats?.hits||0,k:kills(s)};s._v611EffFail=false;}
    function effColor(v){return v>=.88?'#52d284':v>=.72?'#a8cd67':v>=.50?'#dcc95b':v>=.28?'#e49a49':'#e2534b';}
    function updateEff(s){if(!s)return;if(s._v611EffSeed!==(s.scenario?.seed??0)||s._v611Eff==null)resetEff(s);if(s.mode!=='playing'||s.levelComplete||s._v611EffFail)return;const cur={tr:s.stats?.triggers||0,ok:s.stats?.effectiveTriggers||0,h:s.stats?.hits||0,k:kills(s)},l=s._v611EffLast||cur,dtr=Math.max(0,cur.tr-l.tr),dok=Math.max(0,cur.ok-l.ok),dh=Math.max(0,cur.h-l.h),dk=Math.max(0,cur.k-l.k);if(dtr){const good=Math.min(dtr,dok),bad=Math.max(0,dtr-good);s._v611Eff=U.clamp(s._v611Eff+good*.008-bad*.006,0,1);}if(dh)s._v611Eff=U.clamp(s._v611Eff+Math.min(.025,dh*.004),0,1);if(dk)s._v611Eff=U.clamp(s._v611Eff+Math.min(.04,dk*.01),0,1);s._v611EffLast=cur;if(s._v611Eff<.20){s._v611EffFail=true;s.bunker.hp=0;s.ui=s.ui||{};s.ui.message='EFFICIENCY LOST';s.ui.messageT=2.2;}}
    function hud(s,ctx){const {w,h,dpr}=s.viewport,top=s.safe?.top||0,bottom=s.safe?.bottom||0,hp=Math.max(0,Math.ceil(s.bunker?.hp||0)),eff=U.clamp(s._v611Eff??.75,0,1),k=kills(s),map=(s.campaign?.index||0)+1,heat=U.clamp(s.bunker?.heat||0,0,1);ctx.save();ctx.setTransform(dpr,0,0,dpr,0,0);const ph=top+78;ctx.fillStyle='rgba(12,15,12,.96)';ctx.fillRect(0,0,w,ph);ctx.font='800 8px ui-monospace,SFMono-Regular,Menlo,monospace';ctx.textBaseline='top';ctx.fillStyle='#aeb7a2';ctx.textAlign='left';ctx.fillText('HP',12,top+7);ctx.textAlign='center';ctx.fillText(`MAP ${map}/9`,w/2,top+7);ctx.textAlign='right';ctx.fillText('KILLS',w-12,top+7);ctx.font='900 25px ui-monospace,SFMono-Regular,Menlo,monospace';ctx.textBaseline='alphabetic';ctx.textAlign='left';ctx.fillStyle=hp>50?'#f0f0df':hp>25?'#e7bd5e':'#e06459';ctx.fillText(String(hp),12,top+39);ctx.textAlign='center';ctx.fillStyle=effColor(eff);ctx.fillText(`${Math.round(eff*100)}%`,w/2,top+39);ctx.textAlign='right';ctx.fillStyle='#f0f0df';ctx.fillText(String(k),w-12,top+39);ctx.font='800 7px ui-monospace,SFMono-Regular,Menlo,monospace';ctx.textAlign='center';ctx.fillStyle='#aeb7a2';ctx.fillText('EFFICIENCY',w/2,top+49);const bx=12,by=top+57,bw=w-24,bh=10;ctx.fillStyle='#20261f';ctx.fillRect(bx,by,bw,bh);ctx.fillStyle=effColor(eff);ctx.fillRect(bx,by,bw*eff,bh);ctx.strokeStyle='#384138';ctx.strokeRect(bx+.5,by+.5,bw-1,bh-1);for(const q of [.20,.50,.72,.88]){ctx.fillStyle='rgba(15,18,15,.7)';ctx.fillRect(Math.round(bx+bw*q),by,1,bh);}const botH=bottom+42,yy=h-botH;ctx.fillStyle='rgba(12,15,12,.96)';ctx.fillRect(0,yy,w,botH);ctx.font='800 8px ui-monospace,SFMono-Regular,Menlo,monospace';ctx.textBaseline='middle';ctx.fillStyle='#bac1ae';ctx.textAlign='left';ctx.fillText('HEAT',12,yy+17);ctx.textAlign='right';ctx.fillText(`${Math.round(heat*100)}%`,w-12,yy+17);const hx=51,hy=yy+13,hw=Math.max(40,w-102);ctx.fillStyle='#222822';ctx.fillRect(hx,hy,hw,8);ctx.fillStyle=heat>.78?'#dd5949':heat>.55?'#df9c49':'#a9bd66';ctx.fillRect(hx,hy,hw*heat,8);ctx.restore();}

    function installShop(){if(document.getElementById('v611Shop'))return;const css=document.createElement('style');css.textContent=`#v611Shop{position:fixed;inset:0;z-index:80;display:none;align-items:center;justify-content:center;padding:calc(env(safe-area-inset-top) + 14px) 14px calc(env(safe-area-inset-bottom) + 14px);background:rgba(8,10,8,.90);backdrop-filter:blur(4px);-webkit-backdrop-filter:blur(4px)}#v611Shop.show{display:flex}.v611card{width:min(94vw,430px);max-height:92vh;overflow:auto;background:#171c16;border:1px solid #4e5949;border-radius:15px;padding:18px;color:#edf0dc}.v611head{display:flex;justify-content:space-between;align-items:end;gap:12px}.v611ttl{font:900 22px system-ui;margin:0}.v611sup{font:900 20px ui-monospace,monospace;color:#e1c66b}.v611sub{font:700 10px ui-monospace,monospace;color:#98a18f;margin:4px 0 14px}.v611grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.v611up{appearance:none;border:1px solid #48513f;background:#252c21;color:#edf0dc;border-radius:10px;padding:10px;text-align:left}.v611up:disabled{opacity:.38}.v611n{font:900 11px system-ui}.v611m{font:700 9px ui-monospace,monospace;color:#aeb6a0;margin-top:3px}.v611cost{font:900 10px ui-monospace,monospace;color:#e1c66b;margin-top:5px}.v611next{width:100%;margin-top:14px;border:0;border-radius:11px;background:#d7b95e;color:#1b2018;font:900 13px system-ui;padding:14px}`;document.head.appendChild(css);const d=document.createElement('div');d.id='v611Shop';d.innerHTML=`<div class="v611card"><div class="v611head"><div><div class="v611ttl">UPGRADES</div><div class="v611sub" id="v611Result">MAP CLEARED</div></div><div class="v611sup" id="v611Supply">0 SP</div></div><div class="v611grid" id="v611Grid"></div><button class="v611next" id="v611Next">NEXT MAP</button></div>`;document.body.appendChild(d);document.getElementById('v611Next').addEventListener('click',nextMap);}
    const LABEL={caliber:'DAMAGE',burst:'BURST',charge:'CHARGE SPEED',range:'RANGE',cooling:'COOLING',he:'HE BLAST',armor:'ARMOR'};
    function renderShop(s){installShop();const grid=document.getElementById('v611Grid'),sup=document.getElementById('v611Supply');sup.textContent=`${s.save?.supply||0} SP`;grid.innerHTML='';for(const key of Object.keys(LABEL)){const lvl=s.save?.upgrades?.[key]||0,cost=J.Progress.upgradeCost(key,lvl),max=J.CONFIG.campaign.upgrades[key].max,b=document.createElement('button');b.className='v611up';b.disabled=cost==null||(s.save?.supply||0)<cost;b.innerHTML=`<div class="v611n">${LABEL[key]}</div><div class="v611m">LEVEL ${lvl}/${max}</div><div class="v611cost">${cost==null?'MAX':cost+' SP'}</div>`;b.onclick=()=>{if(J.Progress.tryBuyUpgrade(s,key))renderShop(s);};grid.appendChild(b);} }
    function reward(s){if(s._v611Rewarded)return;s._v611Rewarded=true;const map=(s.campaign?.index||0)+1,r=50+map*8+kills(s)*2;s.save.supply=(s.save.supply||0)+r;s.save.totalMapsCleared=(s.save.totalMapsCleared||0)+1;J.Progress.saveNow(s.save);s._v611LastReward=r;}
    function showShop(s){if(s._v611UpgradeShown)return;s._v611UpgradeShown=true;reward(s);installShop();document.getElementById('v611Result').textContent=`MAP ${(s.campaign?.index||0)+1} CLEARED · +${s._v611LastReward||0} SP`;renderShop(s);document.getElementById('v611Shop').classList.add('show');const ov=document.getElementById('overlay');if(ov)ov.classList.add('hidden');}
    function nextMap(){const s=state();if(!s)return;document.getElementById('v611Shop')?.classList.remove('show');J.Scenarios.advance(s);s._v611Rewarded=false;s._v611UpgradeShown=false;resetEff(s);const c=document.getElementById('game');try{J.Particles?.init?.(s);J.Combat?.init?.(s);if(c)J.World.resize(s,c);}catch(_){}s.mode='brief';s.deployed=false;const ov=document.getElementById('overlay'),ti=document.getElementById('title'),su=document.getElementById('sub'),de=document.getElementById('deploy'),re=document.getElementById('restart');if(ti)ti.textContent=s.scenario?.label||`MAP ${(s.campaign?.index||0)+1}`;if(su)su.innerHTML=`Map ${(s.campaign?.index||0)+1}/9<br><span>Line Assault · snelle insertions · upgrades na elke map</span>`;if(de){de.style.display='inline-flex';de.textContent='DEPLOY';}if(re)re.style.display='none';if(ov)ov.classList.remove('hidden');}
    setInterval(()=>{const s=state();if(s?.levelComplete)showShop(s);},140);

    const oldRender=J.Render.render.bind(J.Render);J.Render.render=function(s,ctx){updateEff(s);const out=oldRender(s,ctx);hud(s,ctx);return out;};
    const init=()=>{installShop();const s=state();if(!s||!s.scenario){setTimeout(init,60);return;}resetEff(s);const t=document.getElementById('title'),sub=document.getElementById('sub');if(t)t.textContent='JBD V6.11 · LINE ASSAULT';if(sub)sub.innerHTML='Snelle line-art combat zonder rommelige kaart.<br><span>Stick soldiers · heli/plane insertions · blijvende kraters · upgrades na elke map</span>';};init();
    console.info('JBD v6.11 HUD/efficiency/upgrade flow active');
  };wait();
})();